### ISSUE TITLE
Unknown attribute u'samaccountname' after drop of attributes parameter in 4.2 

### ISSUE THREAD

**Issue by dirks** [dalibo/ldap2pg#164]
Unknown attribute u'samaccountname' after drop of attributes parameter in 4.2 

With release 4.2 the attributes parameter was dropped from the ldap part of the configuration. Here this results in in critical `Unknown attribute u'samaccountname'` errors directly after the ldap search.

4.1 log

```
Doing: ldapsearch -x -D cn=mybinduser,ou=Functional Users,ou=Users,ou=IDIV,dc=idiv,dc=de -W -b ou=AAI,dc=idiv,dc=de -s sub '(memberOf:1.2.840.113556.1.4.1941:=cn=g_r_postgres01-KREINITZ_rw,ou=FunctionalGroups,ou=Groups,ou=IDIV,dc=idiv,dc=de)' sAMAccountName

Got 3 entries from LDAP.
Found role redac t. ed from CN=redac ted,OU=German Centre for Integrative Biodiversity Research,OU=Mitarbeiter,OU=AAI,DC=idiv,DC=de sAMAccountName.
[…]
Found ACL item ddl on KREINITZ.* for * to kreinitz_owner (granted) in LDAP.
[…]
```

4.2 log

```
Doing: ldapsearch -x -D cn=mybinduser,ou=Functional Users,ou=Users,ou=IDIV,dc=idiv,dc=de -W -b ou=AAI,dc=idiv,dc=de -s sub '(memberOf:1.2.840.113556.1.4.1941:=cn=g_r_postgres01-KREINITZ_rw,ou=FunctionalGroups,ou=Groups,ou=IDIV,dc=idiv,dc=de)' sAMAccountName
[ldap2pg.manager     DEBUG] Got 3 entries from LDAP.
[ldap2pg.script   CRITICAL] Failed to process CN=redac t. ed,OU=German Centre for Integra: Unknown attribute u'samaccountname'
```

It might(!) be related to the base search string. The users are in …,ou=AAI,dc… while the groups are in …,ou=IDIV,dc…. Using the dc… as base search string does work for ldapsearch but for some reason not via ldap2pg. With ldapsearch you actually need to omit the ou as it would not find the users which are in the ou=AAI,dc… if the base search string points to ou=IDIV,dc…

```
[ldap2pg.script   CRITICAL] Failed to query LDAP: {'info': '000004DC: LdapErr: DSID-0C09079A, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v23f0', 'desc': 'Operations error'}.
```

**Comment by bersace** [comment]
Hi @dirks thanks for reporting.

Looks like `ldap2pg` properly detect that `sAMAccountName` has to be queried. That's cool. Both `ldapsearch` queries are exactly the same and 3 entries are return in both cases. That may be a bug about attribute name case. I'll invistigate this.

Can you show me the working `ldapsearch` command ?

**Comment by dirks** [comment]
Here is the slightly redacted ldapsearch query and output.

```
-bash-4.2$ ldapsearch -h mydc.idiv.de  -b "dc=idiv,dc=de" -D "cn=mybinduser,ou=Functional Users,ou=Users,ou=IDIV,dc=idiv,dc=de" -x -W '(memberof:1.2.840.113556.1.4.1941:=cn=g_r_postgres01-KREINITZ_rw,ou=FunctionalGroups,ou=groups,ou=IDIV,dc=idiv,dc=de)' samaccountname
Enter LDAP Password: 
# extended LDIF
#
# LDAPv3
# base <dc=idiv,dc=de> with scope subtree
# filter: (memberof:1.2.840.113556.1.4.1941:=cn=g_r_postgres01-KREINITZ_rw,ou=FunctionalGroups,ou=groups,ou=IDIV,dc=idiv,dc=de)
# requesting: samaccountname 
#

# redac t. ed, German Centre for Integrative Biodiversity Research, Mitarb
 eiter, AAI, idiv.de
dn: CN=redac t. ed,OU=German Centre for Integrative Biodiversity Research
 ,OU=Mitarbeiter,OU=AAI,DC=idiv,DC=de
sAMAccountName: redacted
[…]
```

**Comment by joshlk** [comment]
I'm getting this issue as well. I debugged the ldap2pg code and I think this is the issue:

https://github.com/dalibo/ldap2pg/blob/1281c3d27cc8403175d1c1b4b7c0e5dac03b139b/ldap2pg/ldap.py#L68

The returned attribute dictionary looks like:
```
attributes = {'sAMAccountName': [b'joshlk']}
```

But as you lowercase the `path` it looks for the key `samaccountname` in the attributes dict and returns an error.

I have only just started using `ldap2pg` so this may be intentional or I'm using the config wrong, so sorry for the newbie question

**Comment by bersace** [comment]
@joshlk Yes, it's a known bug fixed in master. I'm testing master with @dirks. Expect a 4.3 release today or tomorrow.

**Comment by bersace** [comment]
@joshlk by the way, welcome to `ldap2pg` :-)

**Comment by bersace** [comment]
It's on PyPI. http://ldap2pg.readthedocs.io/en/latest/changelog/#ldap2pg-43

**Comment by dirks** [comment]
I did not encounter this error in 4.3. and 4.3.1 anymore. So I think the issue can be closed.

@joshlk do you still experience this problem?

**Comment by joshlk** [comment]
Yes the bug has gone in v4.3.1

**Comment by bersace** [comment]
Thanks. Let's close :-)

**Comment by jrjsmrtn** [comment]
@bersace the release on PyPI is still 4.10, not 4.3.1.

**Comment by jrjsmrtn** [comment]
forget it, I misread 4.10 as 4.1.0 :-q
