### ISSUE TITLE
Tiny little bug in blacklist ?

### ISSUE THREAD

**Issue by superette** [dalibo/ldap2pg#195]
Hi,

I installed ldap2pg for testing, i don't want to synchronize all my roles and privileges with ldap2pg, but just manage named users on our database, assign to 2 roles : 'dba' and 'analysts'

So i look into the blacklist section and found this problem : 

this works : 
```
postgres:
  blacklist: [postgres, pg_*,bob_*,lol_*,twt_*, a*_ro]
```
this doesn't : 
```
postgres:
  blacklist: [postgres, pg_*,*_adm,*_ro,*_rw]
```

And get me the following error : 
```
Starting ldap2pg 4.6.
Using /home/perette/git/ldap2pg/ldap2pg.yml.
YAML error with /home/perette/git/ldap2pg/ldap2pg.yml: found undefined alias '_adm'
  in "/home/perette/git/ldap2pg/ldap2pg.yml", line 3, column 30
```

it seems the issue appear only if the wildcard is put  first  ? Or maybe i'm doing wrong something else :)

**Comment by superette** [comment]
in fact like that, it works

```
postgres:
  blacklist: [postgres, pg_*,'*_adm','*_rw', '*_ro']
```

**Comment by cbandy** [comment]
Ah, yes. A bare word preceded by `*` is a [YAML alias](http://www.yaml.org/spec/1.2/spec.html#id2786196).

**Comment by bersace** [comment]
@cbandy i added a mention on this gotcha in #200 . YAML error is obvious but still surprising.

**Comment by bsislow** [comment]
Thank you! I am not familiar enough with YAML.

**Comment by bersace** [comment]
@bsislow no worry. A note specific on this case is in the documentation : https://ldap2pg.readthedocs.io/en/latest/postgres/#synchronize-a-subset-of-roles

> A pattern starting with a * must be quoted. Else you’ll end up with a YAML error like found undefined alias.
