### ISSUE TITLE
Failed to query LDAP: {'matched': u'dc=***,dc=***', 'desc': u'No such object'}.

### ISSUE THREAD

**Issue by Gonzant** [dalibo/ldap2pg#205]
Hello, 
I am trying to use ldap2pg but when i execute ldap2pg this happen:

![image](https://user-images.githubusercontent.com/8551597/38786342-b0b55670-40fd-11e8-98d9-c62912283030.png)

The ldap2pg-yml is:
![image](https://user-images.githubusercontent.com/8551597/38786379-ea754136-40fd-11e8-9dea-6d0906aff923.png)
![image](https://user-images.githubusercontent.com/8551597/38786387-fb761ee2-40fd-11e8-88a4-5fd842d32605.png)

Psql and ldapsearch work.

Any help would be appreciated.

Best regards

**Comment by bersace** [comment]
Hi @Gonzant 

This is an LDAP error. The LDAP object is not found. It's like an HTTP 404 ;-)

When running `ldap2pg` with `--verbose` flag, you will see `ldapsearch` commands logged. Copy and adapt it to get it working. Then adapt `ldap2pg.yml`.

Hint : You don't need `attributes: [cn, member]` anymore, `ldap2pg` collects all `_attribute:` and query them automatically. ;-)

**Comment by bersace** [comment]
Hi,

@Gonzant what is the output of the ldapsearch command just above in the logs ?

Usually, `-s sub` includes parent which, in this case includes `dc=colonizacion,dc=gub` which dont have `cn`.

Try `scope: children` or `filter: (cn=*)`. YMMV.

**Comment by bersace** [comment]
@Gonzant do you get it ?

**Comment by Gonzant** [comment]
Yes! It work.

Thank you very much!

Best wishes with ldap2pg!

**Comment by testingash** [comment]
hi, 

I asl came across same issue as, 
Failed to query LDAP: {'matched': 'ou=****,dc=**,dc=**', 'desc': 'No such object'}

I gone throgh above comments but did not understand solution:
**""When running ldap2pg with --verbose flag, you will see ldapsearch commands logged. Copy and adapt it to get it working. Then adapt ldap2pg.yml.""**

Can you elaborate on this point?

**Comment by bersace** [comment]
@testingash if you struggle with YAML, you can narrow the problem to the LDAP query and use ldapsearch to construct the right LDAP query. Once you're satisfied, you can report back the LDAP query in the YAML. Is it clearer for you ?

**Comment by testingash** [comment]
ok. I understand now instead of script file directly can test using direct ldap query  and then port it to YAML. I wanted to create LDAP users in postgres DB.

Thanks for help. really appreciate.

**Comment by testingash** [comment]
Hi,
I reached next level by first using ldapsearch and then getting parameters correct. But next I came across this below:
ldap2pg.yml.
Running in dry mode. Postgres will be untouched.
Inspecting roles in Postgres cluster...
Querying LDAP cn=developers-group,ou=d... (objectclass...
Would create  ash12.
Would create  ashle.
Would create  tt.
Would create developers-group.
Inspecting GRANTs in Postgres cluster...
In dry mode, some owners aren't created, their default privileges can't be determined.
Unhandled error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/ldap2pg/script.py", line 84, in main
    exit(wrapped_main(config))
  File "/usr/local/lib/python3.4/dist-packages/ldap2pg/script.py", line 68, in wrapped_main
    count = manager.sync(syncmap=config['sync_map'])
  File "/usr/local/lib/python3.4/dist-packages/ldap2pg/manager.py", line 213, in sync
    pgacl = self.inspector.fetch_grants(schemas, pgmanagedroles)
  File "/usr/local/lib/python3.4/dist-packages/ldap2pg/inspector.py", line 254, in fetch_grants
    rows = psql(privilege.inspect)
  File "/usr/local/lib/python3.4/dist-packages/ldap2pg/psql.py", line 142, in __call__
    self.cursor.execute(query, *args)
psycopg2.ProgrammingError: syntax error at or near "("
LINE 26:       FILTER (WHERE pro.proname IS NOT NULL) AS procs
                      ^
Please file an issue at https://github.com/dalibo/ldap2pg/issues with full log.

**Comment by bersace** [comment]
@testingash what is the version of Postgres server ?

**Comment by bersace** [comment]
@testingash can you open another issue for this ?
