### ISSUE TITLE
Running as non-superuser

### ISSUE THREAD

**Issue by schmandr** [dalibo/ldap2pg#209]
When connecting to the DB with a non-superuser, an unhandled error occurs (and I was recommended to file an issue):
```
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] SELECT array_agg(column_name::text)
[ldap2pg.psql         DEBUG] FROM information_schema.columns
[ldap2pg.psql         DEBUG] WHERE table_schema = 'pg_catalog' AND table_name = 'pg_authid'
[ldap2pg.psql         DEBUG] LIMIT 1
[ldap2pg.script       ERROR] Unhandled error:
[ldap2pg.script       ERROR] Traceback (most recent call last):
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/script.py", line 87, in main
[ldap2pg.script       ERROR]     exit(wrapped_main(config))
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/script.py", line 51, in wrapped_main
[ldap2pg.script       ERROR]     RoleOptions.update_supported_columns(supported_columns)
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/role.py", line 155, in update_supported_columns
[ldap2pg.script       ERROR]     c for c in RoleOptions.COLUMNS.keys()
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/role.py", line 156, in <listcomp>
[ldap2pg.script       ERROR]     if c in columns
[ldap2pg.script       ERROR] TypeError: argument of type 'NoneType' is not iterable
[ldap2pg.script       ERROR] Please file an issue at https://github.com/dalibo/ldap2pg/issues with full log.
```

Btw, do you recommend using a superuser role? Or which privileges (and grants on tables) would any other role need to run the ldap2pg queries?

**Comment by bersace** [comment]
@schmandr thanks for the report !

Yes, i recommand superuser for now. But maybe `CREATEROLE` is enough if you manage only roles. But for grants, revokes and alter default privileges, you should use a superuser.

**Comment by schmandr** [comment]
OK. Thanks for the info.

**Comment by bersace** [comment]
@schmandr that's a good point. The ability to run ldap2pg without super privileges is nice. What do you expect from `ldap2pg` if it can't remove a role because of owned objects ? Dose DROP ROLE revoke grants on that roles ?

**Comment by bersace** [comment]
@schmandr do you require to run ldap2pg as non-superuser because you are on a cloud ?

**Comment by bersace** [comment]
> Doing a GRANT user1 TO nonsuperuser before the REASSIGN and DROP OWNED BY should work though.

@schmandr thanks for pointing this. `ldap2pg` should do this for non superuser.

**Comment by bersace** [comment]
@schmandr looks like everything works great as long as the role creator is also the owner of objects.

**Comment by bersace** [comment]
Released.
