### ISSUE TITLE
Stdout of only modified data

### ISSUE THREAD

**Issue by mhagander** [dalibo/ldap2pg#219]
Hi!

Right now, running ldap2pg will always output data on the standard output, even if quiet mode is specified.

It would be very good to have output modes for:

1. Something that only prints errors, and nothing else. As long as everything works, nothing at all is printed.
2. Something that prints all changes, but no status messages. As long as nothing has changed, nothing is printed. If something has changed, the change is printed. And of course, if something goes wrong, errors are printed.

When running it in a cronjob, this makes for proper "change notifications", instead of just having to pipe the whole thing to /dev/null.

**Comment by bersace** [comment]
Hi @mhagander thanks for the feedback !

> Right now, running ldap2pg will always output data on the standard output, even if quiet mode is specified.

Actually it's stderr, can you confirm me you talk about log messages ?

There is a `--check` switch that triggers exit code `1` when there is changes. Note that configuration errors triggers an exit code `2`. Does this help you ? I should document exit codes.

> Something that prints all changes, but no status messages.

That's a good idea to have a silent mode with only errors. I suggest to add warnings too. This is an issue, ldap2pg logs warnings, but they are lost in the big log.

Do you have an idea of CLI switches for this ? I'm thinking of cumulative `-v` and `-q`.

- Defaults : errors + warnings + changes + info
- `-v` -> defaults + debug
- `-q` -> defaults - info
- `-qq` -> defaults - info - changes
- `-qqq` -> defaults - info - changes - warnings

Should this behaviour fit your needs ?

**Comment by mhagander** [comment]
Yeah, you're probably right about stderr/stdout -- I am talking about log messages.

I know about the --check, but the point is if I run it for example in cron, then cron will send an email if there is any printed output. Which is a good way for "simple trapping of errors".

And yes, those suggestions would fit my needs.

Thanks!

**Comment by bersace** [comment]
Let's close. @mhagander please reopen if you have an issue with this :-)
