### ISSUE TITLE
Add __temp_on_database__ privilege

### ISSUE THREAD

**Issue by madtibo** [dalibo/ldap2pg#234]
The creation of temporary table is not managed by ldap2pg.

It would be good, in the default yml file, if this temporary object creation is not removed :
  * `REVOKE TEMP ON DATABASE <db> FROM <role>;`

**Comment by bersace** [comment]
Hmm, actually, it is done already :-) It's [`__temporary__`](https://ldap2pg.readthedocs.io/en/latest/wellknown/#privilege-__temporary__).

Je ferme.
