### ISSUE TITLE
can't revoke a custom privilege

### ISSUE THREAD

**Issue by ankravch** [dalibo/ldap2pg#242]
I follow an example from https://ldap2pg.readthedocs.io/en/latest/privileges/#defining-custom-privilege
to define a custom privilege:

```python
inspect query for datacl must return a rowset with two columns, the first is unused, the second is the name of grantee.
```

```python
privileges:
  my_grant_all_on_database_privilege:
    type: datacl
    grant: GRANT ALL ON DATABASE {database} TO {role};
    revoke:  REVOKE ALL ON DATABASE {database} FROM {role};
    inspect: SELECT 1, 'admin'; 

sync_map:
- grant:
    database: mydb
    schema: public
    privilege: my_grant_all_on_database_privilege
    role: admin
```
The privilege does get granted, but it can't be revoked. My question is what would be a proper "inspect" definition in this case?

**Comment by bersace** [comment]
Hi @ankravch ! Thanks for the report. :-)

The static inspect you wrote tells ldap2pg that `my_grant_all_on_database_privilege` is granted to `admin`.

The sync_map tells ldap2pg that `my_grant_all_on_database_privilege` must be granted to `admin`.

Thus, there is nothing to do, right ?

Note, you can skip `schema` when granting  `datacl` privileges.

**Comment by ankravch** [comment]
Hmm... How would you tell ldap2pg that ```my_grant_all_on_database_privilege``` must be revoked from ```admin```?

**Comment by ankravch** [comment]
```python
privileges:
  connect_only:
    -__connect__

  my_grant_all_on_database_privilege:
    type: datacl
    grant: GRANT ALL ON DATABASE {database} TO {role};
    revoke:  REVOKE ALL ON DATABASE {database} FROM {role};
    inspect: SELECT 1, 'admin'; 

sync_map:
- grant:
    database: mydb
    schema: public
    privilege: connect_only
    role: admin
```
This one grants ```connect_only``` but still does not revoke ```my_grant_all_on_database_privilege```.

**Comment by bersace** [comment]
> Hmm... How would you tell ldap2pg that my_grant_all_on_database_privilege must be revoked from admin?

There is no explicit revoke. If `inspect` find a grant that is not required by any `sync_map:grant`, it is revoked.

``` console
$ cat my-test-ldap2pg.yml
postgres:
  roles_query: null
privileges:
  connect: [__connect__]
$ ldap2pg -c my-test-ldap2pg.yml
Starting ldap2pg 4.14.
Using /home/bersace/src/dalibo/ldap2pg/my-test-ldap2pg.yml.
Empty synchronization map!
Running in dry mode. Postgres will be untouched.
Inspecting roles in Postgres cluster...
Roles introspection disabled.
Inspecting GRANTs in Postgres cluster...
Would revoke __connect__ on appdb from public.
Would revoke __connect__ on nonsuperdb from public.
Would revoke __connect__ on olddb from public.
Would revoke __connect__ on postgres from public.
Would revoke __connect__ on template1 from public.
Comparison complete.
```

**Comment by bersace** [comment]
@ankravch I think there is something odd. I tried to have your configuration right and get the *Would revoke my_acl*. Here it is:

``` console
$ cat my-test-ldap2pg.yml 
privileges:
  connect_only:
  - __connect__

  my_grant_all_on_database_privilege:
    type: datacl
    grant: GRANT ALL ON DATABASE {database} TO {role};
    revoke:  REVOKE ALL ON DATABASE {database} FROM {role};
    inspect: "SELECT NULL, 'admin';"

sync_map:
- role: admin
- grant:
    privilege: connect_only
    role: admin
$ ldap2pg -c my-test-ldap2pg.yml                                                                                  [100/7912]
Starting ldap2pg 4.14.                                  
Using /home/bersace/src/dalibo/ldap2pg/my-test-ldap2pg.yml.
Running in dry mode. Postgres will be untouched.         
Inspecting roles in Postgres cluster...                  
Inspecting GRANTs in Postgres cluster...
In dry mode, some owners aren't created, their default privileges can't be determined.
Would revoke my_grant_all_on_database_privilege on appdb from admin.
Would revoke __connect__ on appdb from public.
Would revoke my_grant_all_on_database_privilege on nonsuperdb from admin.
Would revoke __connect__ on nonsuperdb from public.
Would revoke my_grant_all_on_database_privilege on olddb from admin.
Would revoke __connect__ on olddb from public.
Would revoke my_grant_all_on_database_privilege on postgres from admin.
Would revoke __connect__ on postgres from public.
Would revoke my_grant_all_on_database_privilege on template1 from admin.
Would revoke __connect__ on template1 from public.
Would grant __connect__ on appdb to admin.
Would grant __connect__ on nonsuperdb to admin.
Would grant __connect__ on olddb to admin.
Would grant __connect__ on postgres to admin.
Would grant __connect__ on template1 to admin.
Generated 99 querie(s).
Comparison complete.
$
```

Note that without actually creating *admin* in the cluster, i don't get *revoke*.

Does it help you ? I think that cookbook should have a *How to revoke* section. Please keep this issue opened.

**Comment by ankravch** [comment]
Yes it helped. I had to switch from
```python
inspect: SELECT 1, 'admin';
```
to
```python
inspect: "SELECT NULL, 'admin';"
```
and now I am able to revoke ```my_grant_all_on_database_privilege```.

**Comment by bersace** [comment]
@ankravch oh, yes, you're right. `schema` is not actually ignore. I must fix that ! Thanks for pointing it.

> and now I am able to revoke my_grant_all_on_database_privilege.

Good ! :) I'm listing here what should be done to help other users in you're situation. Please let me know if something is missing or wrong :

### Tasks

 - [ ] Fix schema not ignored in datacl privileges inspect.
 - [ ] Update Cookbook about revocation of privileges.
 - [ ] Detect grants on users not yet in managed roles (in dry run).

**Comment by bersace** [comment]
Ok, let's close. @ankravch don't hesitate to comment #251 if you find the doc is not clear enough. Thanks !
