### ISSUE TITLE
ldap2pg command not found

### ISSUE THREAD

**Issue by SamyOteroGlez** [dalibo/ldap2pg#287]
Basically after following this [https://ldap2pg.readthedocs.io/en/latest/install/#pure-python](https://ldap2pg.readthedocs.io/en/latest/install/#pure-python) installation process, when I run `ldap2pg --version` or any other `ldap2pg` command I get `command not found`.

I am installing it inside a vagrant vm. I am running a dockerized active directory and postgresql db in a vagrant vm.

Not sure if it helps but here is the vagrantfile:
```
Vagrant.configure("2") do |config|
    # Install docker-compose plugin
    config.vagrant.plugins = [
        "vagrant-docker-compose",
        "vagrant-vbguest"
    ]

    # Vm box basic configuration
    config.vm.box = "ubuntu/bionic64"
    # Geoserver
    config.vm.network "forwarded_port", guest: 8093, host: 8093
    # Posgis db
    config.vm.network "forwarded_port", guest: 65433, host: 65433
    # Test active directory
    config.vm.network "forwarded_port", guest: 11389, host: 11389

    # Provisioning the vm
    config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.gui = false
        vb.cpus = 2
        vb.memory = 4096
    end
    config.vm.provision :docker
    config.vm.provision :docker_compose, compose_version: "1.24.1"

    # Active directory
    config.vm.provision :shell,
        keep_color: true,
        privileged: false,
        run: "always",
        inline: <<-SCRIPT
            cd /vagrant/ldap/
            docker-compose up -d
        SCRIPT
    # Geoserver and posgis db
    config.vm.provision :shell,
        keep_color: true,
        privileged: false,
        run: "always",
        inline: <<-SCRIPT
            cd /vagrant/gis_droplet/
            docker-compose up -d
        SCRIPT
end

```

Regards,
Sam

**Comment by bersace** [comment]
Hi @SamyOteroGlez , Thanks for the report !!

Do you have `/usr/local/bin` in your `PATH` ? Debian distributed `pip` installs in `/usr/local` to not clash with files installed by dpkg.

**Comment by SamyOteroGlez** [comment]
Hi @bersace,
It should be since I also have `composer` installed, it works as expected.

**Comment by SamyOteroGlez** [comment]
@bersace but for some reason after the install ldap2pg is not in /usr/local/bin/

**Comment by SamyOteroGlez** [comment]
Got it working!!!
For some reason, I had to install it as `sudo` and add the `-H` tag.
`$/ sudo -H pip3 install ldap2pg`
and after that:
`$/ sudo pip3 install psycopg2-binary`

Thanks!!!!!

I guess this can be closed.

**Comment by bersace** [comment]
Hi,

Yes, the doc may be subtle, but the prompt is a `#` instead of `$`, which mean root shell.

The best option is to use `sudo -i` to have a clean root environment.

``` console
$ sudo -i pip3 install ldap2pg psycopg2-binary
```

Some people are used to `sudo su` for that prupose, but `-i` is enough.

If you want to install as user rather than root, use `pip install --user` without sudo, and ensure `~/.local/bin` is in your `PATH`.

I think this issue is all about sudo and pip, not ldap2pg, thus I won't update the installation doc. Would you ?

Thanks for sharing your solution.
