### ISSUE TITLE
Owner per Database

### ISSUE THREAD

**Issue by wernermarcel77** [dalibo/ldap2pg#288]
Hello, 

one of my database hosts has 12 Databases on it.
DB01 - DB07 should be managed by ldap2pg the other database leave as it is. 

These 7 Databases has an Role: 
- pd_db0[1-7]_admin
- pd_db0[1-7]_write 
- pd_db0[1-7]_read

As i understand/ test only if a owner is set the default privilidges will be assigned. 

We has 7 Files for the 7 Databases, included the owner and the db like: 

databases_query: [db01,postgres]
owners_query: [pd_db01_admin]

Is there another way to get this running in one File or another query regarding the owner <- > db match ?

Thanks for your answer .
rg
marcel

**Comment by bersace** [comment]
Hi @wernermarcel77, thanks for reaching.

You may find some information at https://ldap2pg.readthedocs.io/en/latest/postgres/#per-schema-owners-example

ldap2pg accepts a list of owner **per schema**. Thus, you could write a SELECT returning all managed schemas in a database and their respective owner. 

Does it make sens to you ?

**Comment by wernermarcel77** [comment]
Hmm yes it make sence for shema / owner in DB but not for the DB it self or miss-understanding it ?

**Comment by bersace** [comment]
@wernermarcel77 the schemas_query is executed once per database. Thus you could write a SELECT using `current_database()` to adapt the results. Here is a dumb example usage of `current_database()`.

``` sql
WITH db AS (
  SELECT current_database() as dbname
)
SELECT nspname, array_agg(dbname || rolname)
  FROM pg_namespace, pg_roles, db
WHERE rolname NOT LIKE 'pg_%'
  GROUP BY nspname;
```

**Comment by bersace** [comment]
Hi @wernermarcel77 , I misled you, it's not `owners_query` but `schemas_query` that allows to declare per-schemas owner. `owners_query` is global and executed once. See https://ldap2pg.readthedocs.io/en/latest/postgres/#per-schema-owners-example .

Please keep this issue opened until I fixed the doc.

**Comment by bersace** [comment]
@wernermarcel77 would you mind to close the issue if you're ok with the documentation ?

**Comment by wernermarcel77** [comment]
Hi
Yes I’m ok thanks a lot !
EG
Marcel 

Von meinem iPhone gesendet
