### ISSUE TITLE
Enable case sensitiveness on ldap2pg

### ISSUE THREAD

**Issue by zurikus** [dalibo/ldap2pg#289]
Hello  Étienne,

Can we enable case sensitiveness support within Ldap2pg package? 

We have upper and lower case sAMAccountName
http://joxi.ru/D2P9nQ3IqQDkRA

But looks like Ldap2pg is not able to handle it
as I can see lowercase users on PSQL side: 
http://joxi.ru/Q2K9Z7LILnVXRr

IMHO, to enable case sensitiveness support for PSQL Ldap2pg just need to pass usernames or sAMAccountName or cn from LDAP or statically defined role name from .yaml to PSQL within double quotes "DD474HD".

For example: 
```
psql> create role "TOTO";
psql> create role "ToTo"; 
```

But we need to use double quotes while dropping users and roles as well then.

```
psql> drop role "ToTo";
psql> drop role "TOTO";
```

**Comment by bersace** [comment]
Thanks @zurikus 

There is something odd. In dev env:

``` console
$ docker-compose up -d
Creating network "ldap2pg_default" with the default driver
Creating ldap2pg_postgres_1 ... done
Creating ldap2pg_ldap_1     ... done
$ psql
psql (11.5 (Debian 11.5-1+deb10u1))
Saisissez « help » pour l'aide.

postgres=# create role TOTO;
CREATE ROLE
postgres=# create role toto;
ERROR:  role "toto" already exists
postgres=# 
$
```

How can Postgres be case sensitive for roles ?

**Comment by zurikus** [comment]
Same as for users. Roles and users have same concept. Users are roles with LOGIN permissions.
https://www.postgresql.org/docs/11/user-manag.html

By default postgres create user or role in lowercase (without double quotes), but if you will use double quotes it will looks on casesensitivness.

So 

psql> create role "TOTO";
psql> create role "ToTo";
psql> create role "toto";

all will executes successfully as it will be different roles.

**Comment by bersace** [comment]
Hi @zurikus thanks for pointing this ! That's a major change.

**Comment by bersace** [comment]
@zurikus, It's merged, released. Please test, especially renaming. I still suggest to avoid capital in role name since it violate SQL standard !

**Comment by zurikus** [comment]
Hello Étienne,
worked like a charm!
Thank you!

`$ ldap2pg -c /etc/ldap2pg/ldap2pg.yml
Starting ldap2pg 5.1.
Using /etc/ldap2pg/ldap2pg.yml.
Running in dry mode. Postgres will be untouched.
Inspecting roles in Postgres cluster...
Querying LDAP ou=.custom,dc=f10,dc=clo... (&(objectCla...
Querying LDAP ou=.custom,dc=f10,dc=clo... (&(objectCla...
Querying LDAP ou=.custom,dc=f10,dc=clo... (&(objectCla...
Querying LDAP ou=.custom,dc=f10,dc=clo... (&(objectCla...
Querying LDAP ou=.custom,dc=f10,dc=clo... (&(objectCla...
Querying LDAP ou=.custom,dc=f10,dc=clo... (&(objectCla...
Querying LDAP ou=.custom,dc=f10,dc=clo... (&(objectCla...
Role gooddeeds_md already exists in cluster. Reusing.
Would rename dd474hd to DD474HD.
Would rename vb263ea to VB263EA.
Would rename ve665rb to VE665RB.
Would rename xx582hj to XX582HJ.
Would rename zu459vb to ZU459VB.
Inspecting GRANTs in Postgres cluster...
In dry mode, some owners aren't created, their default privileges can't be determined.
Comparison complete.
13:07 233 postgres@psql1.cms.faptebune.md> /var/lib/postgresql
$ ldap2pg -c /etc/ldap2pg/ldap2pg.yml --real
Starting ldap2pg 5.1.
Using /etc/ldap2pg/ldap2pg.yml.
Running in real mode.
Inspecting roles in Postgres cluster...
Querying LDAP ou=.custom,dc=f10,dc=clo... (&(objectCla...
Querying LDAP ou=.custom,dc=f10,dc=clo... (&(objectCla...
Querying LDAP ou=.custom,dc=f10,dc=clo... (&(objectCla...
Querying LDAP ou=.custom,dc=f10,dc=clo... (&(objectCla...
Querying LDAP ou=.custom,dc=f10,dc=clo... (&(objectCla...
Querying LDAP ou=.custom,dc=f10,dc=clo... (&(objectCla...
Querying LDAP ou=.custom,dc=f10,dc=clo... (&(objectCla...
Role gooddeeds_md already exists in cluster. Reusing.
Rename dd474hd to DD474HD.
Rename vb263ea to VB263EA.
Rename ve665rb to VE665RB.
Rename xx582hj to XX582HJ.
Rename zu459vb to ZU459VB.
Inspecting GRANTs in Postgres cluster...
Synchronization complete.
`
