### ISSUE TITLE
Glob Pattern Wildcard in Blacklist as a Prefix

### ISSUE THREAD

**Issue by bsislow** [dalibo/ldap2pg#302]
Some of the template information you requested isn't necessarily relevant for this case. Please let me know what other information you may need as we progress.

I noticed that you cannot use a prefix of a wildcard in the blacklist glob patterns - for example:
```
*user
```

I noticed you can only do this:
```
user*
```

Can you add prefix glob wildcards? Is there something I am doing wrong?

**Comment by bersace** [comment]
In YAML, `*user` has a meaning, you should quote it. cf. #195
