### ISSUE TITLE
Maintaining rolconfig Attributes for Login Roles

### ISSUE THREAD

**Issue by bsislow** [dalibo/ldap2pg#303]
We are currently working on replacing manually created login roles with LDAP-based roles. Some of our manually-created roles have attributes associated with them such as:

```
postgres=# select rolname,rolconfig from pg_roles;
          rolname          |                           rolconfig
---------------------------+---------------------------------------------------------------
 user1                     | {search_path=someschema,default_tablespace=some_data,work_mem=64MB}
 user2                     | {work_mem=128MB}
 user3                     | {log_temp_files=-1,work_mem=512MB}
 user4                     | {log_temp_files=-1}
```

User names were of course anonymized for security purposes.

When the users are recreated with ldap2pg, these configurations will be lost - and I do not know how to maintain them. Can you help?

**Comment by bersace** [comment]
Hi Bob :-)

ldap2pg does not yet support rolconfig but should keep rolconfig as is. Why are roles *recreated* ? Would you mind to share ldap2pg --verbose logs ?

**Comment by bsislow** [comment]
Actually, you are correct, they are _not_ recreated - but simply "Nothing to do." Thank you!
