### ISSUE TITLE
Config file is searched at the wrong place

### ISSUE THREAD

**Issue by guruguruguru** [dalibo/ldap2pg#319]
I am not sure if this is a bug but ldap2pg is (in my opinion) looking for the wrong config file:

[ldap2pg.config        INFO] Starting ldap2pg 5.0.
[ldap2pg.config       DEBUG] Trying ./ldap2pg.yml.
[ldap2pg.config       DEBUG] Trying /home/postgres/.config/lda2pg.yml.
[ldap2pg.config       DEBUG] Trying /etc/ldap2pg.yml.
[ldap2pg.config       DEBUG] No configuration file found.

in every place it looks for ldap2pg.yml, except for the .config folder in the home directory, here it searches lda2pg.yml, this does not make any sense to me.

**Comment by bersace** [comment]
Good catch ! :-)

**Comment by guruguruguru** [comment]
@bersace don't you also think it would be wise to cancel the run if there is absolutely no config? In my case it emptied the whole test database ;-)
