### ISSUE TITLE
Cancel Run if no config at all is found

### ISSUE THREAD

**Issue by guruguruguru** [dalibo/ldap2pg#321]
Hi,

again I am not sure if this behaviour is intendend. If there is no Configuration at all (no config file, no config from stdin) will lead to removal of almost all roles. 
Do you think it is possible to include such a feature? I think especially in automated environments this could lead to disaster.

I would be happy to further discuss this. 

Regards,
Dennis

**Comment by bersace** [comment]
@guruguruguru you're right.

I suggest that, to effectively purge an instance from any roles, an empty sync_map must be explicitly defined :

``` console
$ echo 'sync_map: []' | ldap2pg -c -
...
Empty synchronization map!                                            
...
$
```

On empty or unfound configuration, ldap2pg fails explicitly:

``` console
$ ldap2pg -c /dev/null
Configuration is empty. There nothing to synchronize.
$ ldap2pg
No configuration found.
$
```

Is this good ?

**Comment by guruguruguru** [comment]
@bersace this would be great!
