### ISSUE TITLE
RPM for PG12

### ISSUE THREAD

**Issue by guruguruguru** [dalibo/ldap2pg#323]
Good morning,

do you know why RPMs are available in the PG11 repo but not in the PG12 repo? What can we do to get the RPM in the PG12 Repository as well?

PG11: https://yum.postgresql.org/11/redhat/rhel-7-x86_64/
PG12: https://yum.postgresql.org/12/redhat/rhel-7-x86_64/

Thanks,
Dennis

**Comment by bersace** [comment]
I don't have access to yum.postgresql.org repository. This repository is maintained by a team of PGDG members, including Devrim Gunduz.

yum.postgresql.org has its own issue tracker : https://redmine.postgresql.org/projects/pgrpms/

Did you try with the unified repository ?

Anyway, we at Dalibo have our own YUM repository : https://yum.dalibo.org/labs/ . This is where we publish upstream rpm. This repository only has packages for CentOS7. For ldap2pg, I let PGDG build and publish RPMs. 

If you want, I can upload rpms to https://yum.dalibo.org/labs/ . I don't have access to an RHEL7 container nor repositories. Thus I could only build RPMs for CentOS 7.

**Comment by guruguruguru** [comment]
Hi @bersace 
we are mirroring the official yum repos and we do not want too many different repos mirrored but thanks for the offer! As pgbackrest is missing as well in the repos right now I assume that there is something going wrong.

Regards,
Dennis

**Comment by bersace** [comment]
Hi @guruguruguru 

> we are mirroring the official yum repos and we do not want too many different repos mirrored 

Agree. That's why we prefer PGDG repository if possible.

Let me know if you have updates on pgrpms redmine.

Regards,

**Comment by guruguruguru** [comment]
Created an Issue there: https://redmine.postgresql.org/issues/5376

**Comment by bersace** [comment]
Thanks Dennis !

**Comment by guruguruguru** [comment]
@bersace All this has to do with the new common repo but I am not really happy with it, as the ldap2pg rpms have dependencies on the pg-version (i dont know if this is needed). So i opened another ticket: https://redmine.postgresql.org/issues/5392

**Comment by bersace** [comment]
@guruguruguru thanks for the feedback. In the meantime, this may be helpful to ship upstream ldap2pg rpms for CentOS7 in our repos. What do you think of this ?

**Comment by guruguruguru** [comment]
Well right now I created a workaround in puppet, so ldap2pg gets only installed if PG > 10, this is not perfect but enoght for me right now as we are still in testing phase with ldap2pg

**Comment by bersace** [comment]
@guruguruguru ok, just let me know :-)

**Comment by bersace** [comment]
@guruguruguru any updates on packaging status ?

**Comment by bersace** [comment]
Closing. Please reopen if updates.

**Comment by guruguruguru** [comment]
@bersace hey I know this issue is closed, but again there are no new ldap2pg packages in the postgres-common repo.

[   ] python3-ldap2pg-5.4-2.rhel7.x86_64.rpm                        2020-11-18 10:12   77K  
[   ] python3-ldap2pg-5.5-1.rhel7.x86_64.rpm                        2021-04-27 14:34   82K

those two are available.

**Comment by bersace** [comment]
Hi @guruguruguru . Packaging of postgres-common in managed by PGDG at https://redmine.postgresql.org/projects/pgrpms

**Comment by guruguruguru** [comment]
@bersace https://redmine.postgresql.org/issues/6773
