### ISSUE TITLE
Update local role inherit cookbook [was: Quiet Ouput]

### ISSUE THREAD

**Issue by guruguruguru** [dalibo/ldap2pg#324]
Good morning,

we are running ldap2pg in a cronjon right now and cron gives us the following output even though it is running in quiet mode:

Role ampua_adddb01_app already exists in cluster. Reusing.
Role ampua_test_read already exists in cluster. Reusing.
Role ampua_test_owner already exists in cluster. Reusing.
Role ampua_adddb01_owner already exists in cluster. Reusing.
Role ampua_adddb01_read already exists in cluster. Reusing.
Role ampua_test_app already exists in cluster. Reusing.

Is it possible to suppress this as well? I would like to have only errors, these are warnings or info i would say.

Thanks,
Dennis

**Comment by bersace** [comment]
Hi @guruguruguru,

This warnings tells you that theses roles should be returned by `managed_roles_query` but aren't.

ldap2pg warns you because these roles won't be dropped by ldap2pg if they are remove from LDAP directory.

**Comment by guruguruguru** [comment]
Hi @bersace ,

these roles are local roles (https://github.com/dalibo/ldap2pg/issues/315) that should be granted to ldap roles but not be managed by ldap2pg.

maybe I just did something wrong with it?

Regards,
Dennis

**Comment by bersace** [comment]
Ok. ldap2pg has somewhat reversed the direction of roles memberships. ldap2pg manages children of roles while Postgres manage parents. This leads to some harder to understand situation.

It's documented here https://ldap2pg.readthedocs.io/en/latest/cookbook/#inherit-unmanaged-role

I'm thinking of changing how ldap2pg manages memberships to be more consistent with PostgreSQL and make this case easier. As of now, I'm not sure how this could break configuration.

**Comment by bersace** [comment]
Actually, we already had this discussion in #315 :-)

**Comment by guruguruguru** [comment]
@bersace yes thats why i linked #315 ;-) I still dont really get it, should the warnings go away?
If I understand the documentation correct I need to create the local roles but still have to define them in ldap2pg.yml to be able to use them as parent group?

I create the roles:

`psql -c 'create role ampua_test_owner nologin noinherit;'
psql -c 'create role ampua_test_app nologin;'
psql -c 'create role ampua_test_read nologin;'
psql -c 'grant test_owner to ampua_test_owner;'
psql -c 'grant test_app to ampua_test_app;'
psql -c 'grant test_read to ampua_test_read;'`

and then put this in ldap2pg.yml:

`- roles: 
  - name: ampua_test_owner
    options: NOINHERIT
  - name: ampua_test_app
  - name: ampua_test_read
  - name: ldap_roles
`

**Comment by bersace** [comment]
@guruguruguru I guess that these roles should inherit from `ldap_roles` too.

``` yaml
- roles:
  - name: ldap_roles
  - names:
    - ampua_test_app
    - ampua_test_read
    parent: ldap_roles
  - name: ampua_test_owner
    options: NOINHERIT
    parent: ldap_roles
```

I think I should update cookbook for this. Would you mind to confirm this ?

**Comment by guruguruguru** [comment]
Yes this works! Thanks a lot!

**Comment by bersace** [comment]
Ok, I need to update cookbook. Please keep this issue opened. Do you think #315 is ok ?

**Comment by guruguruguru** [comment]
Yes!
