### ISSUE TITLE
Ldap2pg error

### ISSUE THREAD

**Issue by mignaneB** [dalibo/ldap2pg#325]
Hi, when i ran ldap2pg i got those following errors :

```
Starting ldap2pg 5.2.
Using /root/ldap2pg.yml.
Unhandled error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ldap2pg/script.py", line 94, in main
    exit(wrapped_main(config))
  File "/usr/local/lib/python3.5/dist-packages/ldap2pg/script.py", line 26, in wrapped_main
    config.load()
  File "/usr/local/lib/python3.5/dist-packages/ldap2pg/config.py", line 548, in load
    self.merge(file_config=file_config, environ=os.environ, args=args)
  File "/usr/local/lib/python3.5/dist-packages/ldap2pg/config.py", line 564, in merge
    args=args,
  File "/usr/local/lib/python3.5/dist-packages/ldap2pg/config.py", line 288, in process
    return self.processor(value)
  File "/usr/local/lib/python3.5/dist-packages/ldap2pg/validators.py", line 350, in syncmap
    return [mapping(v) for v in value]
  File "/usr/local/lib/python3.5/dist-packages/ldap2pg/validators.py", line 350, in <listcomp>
    return [mapping(v) for v in value]
  File "/usr/local/lib/python3.5/dist-packages/ldap2pg/validators.py", line 256, in mapping
    value['roles'] = [rolerule(r) for r in value['roles']]
  File "/usr/local/lib/python3.5/dist-packages/ldap2pg/validators.py", line 256, in <listcomp>
    value['roles'] = [rolerule(r) for r in value['roles']]
  File "/usr/local/lib/python3.5/dist-packages/ldap2pg/validators.py", line 149, in rolerule
    return RoleRule(**rule)
TypeError: __init__() got an unexpected keyword argument 'name_match'
Please file an issue at https://github.com/dalibo/ldap2pg/issues with full log.
```

there is the content of my ldap2pg.yml : 

``` yaml
- ldap:
    base: cn=dba,ou=nss,dc=scytalelabs,dc=com
    filter: '(objectClass=*)'
    attributes: [cn, member]
  roles:
  - name_attribute: cn
    name_match: dba
    options: SUPERUSER LOGIN
  - member_attribute: member
    options: LOGIN
```

**Comment by bersace** [comment]
Hi @mignaneB . Thanks for the report. I'll fix this.

You may work around the bug with:

``` yaml
- ldap:
    ...
    filter: '(cn=dba)'
  roles:
  - name: "{cn}"
    options: SUPERUSER LOGIN
```

Your YAML has some oddities, ldap2pg should raise proper error for you.

Please keep this issue opened.

**Comment by mignaneB** [comment]
oh ok i see. 
now i have : Failed to connect: FATAL:  role "root" does not exist when i run ldap2pg

**Comment by bersace** [comment]
@mignaneB could you post a log output ?

**Comment by mignaneB** [comment]
i used ldap2pg --verbose and there is the output:
[ldap2pg.config        INFO] Starting ldap2pg 5.2.
[ldap2pg.config       DEBUG] Trying ./ldap2pg.yml.
[ldap2pg.config        INFO] Using /root/ldap2pg.yml.
[ldap2pg.config       DEBUG] Read verbosity from argv.
[ldap2pg.config       DEBUG] Read sync_map from YAML.
[ldap2pg.config       DEBUG] Drop unused hidden privilege __connect__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __create_on_schemas__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_delete_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_execute_on_functions__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_insert_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_references_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_select_on_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_select_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_trigger_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_truncate_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_update_on_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_update_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_usage_on_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_usage_on_types__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __delete_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __execute_on_all_functions__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __global_default_execute_on_functions__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __insert_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __references_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __select_on_all_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __select_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __temporary__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __trigger_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __truncate_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __update_on_all_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __update_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __usage_on_all_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __usage_on_schemas__
[ldap2pg.config       DEBUG] Configuration loaded.
[ldap2pg.script       DEBUG] Setting up LDAP client.
[ldap2pg.ldap         DEBUG] Found rcfile /etc/ldap/ldap.conf.
[ldap2pg.ldap         DEBUG] Read TLS_CACERT from /etc/ldap/ldap.conf.
[ldap2pg.ldap         DEBUG] Read ldap_version from /etc/ldap/ldap.conf.
[ldap2pg.ldap         DEBUG] Read SIZELIMIT from /etc/ldap/ldap.conf.
[ldap2pg.ldap         DEBUG] Read TIMELIMIT from /etc/ldap/ldap.conf.
[ldap2pg.ldap         DEBUG] Read DEREF from /etc/ldap/ldap.conf.
[ldap2pg.ldap         DEBUG] Read BASE from /etc/ldap/ldap.conf.
[ldap2pg.ldap         DEBUG] Read URI from /etc/ldap/ldap.conf.
[ldap2pg.ldap         DEBUG] Ignoring: [Errno 2] No such file or directory: '/root/ldaprc'
[ldap2pg.ldap         DEBUG] Ignoring: [Errno 2] No such file or directory: '/root/.ldaprc'
[ldap2pg.ldap         DEBUG] Connecting to LDAP server ldap://127.0.0.1/.
[ldap2pg.ldap         DEBUG] Trying simple bind.
[ldap2pg.ldap         DEBUG] Doing: ldapwhoami -x
[ldap2pg.script       WARNI] Running in dry mode. Postgres will be untouched.
[ldap2pg.psql         DEBUG] Connecting to Postgres libpq default.
[ldap2pg.script       CRITI] Failed to connect: FATAL:  role "root" does not exist

**Comment by bersace** [comment]
It looks like you're running ldap2pg as root. Try running it as postgres or using TCP.

``` console
$ sudo -u postgres ldap2pg -v
...
$ PGHOST=localhost ldap2pg -v
...
```

See https://ldap2pg.readthedocs.io/en/latest/cli/#environment-variables

I should better document the configuration of PostgreSQL connection.

**Comment by mignaneB** [comment]
thanks i ran it as postgres, 
i got this : 
Starting ldap2pg 5.2.
Empty synchronization map!
Running in dry mode. Postgres will be untouched.
Inspecting roles in Postgres cluster...
Nothing to do.
Comparison complete.
postgres@ubuntu:~$ 

it's good but no new role has been created may be i'll have to review my ldap2pg.yaml

**Comment by bersace** [comment]
@mignaneB what is your ldap2pg.yml file ? *Empty synchronisation map* means you didn't define any roles for ldap2pg either static or from an LDAP query.

**Comment by mignaneB** [comment]
do you have an example with a sync map defined with a ldap query?

**Comment by bersace** [comment]
@mignaneB yep :

https://github.com/dalibo/ldap2pg/blob/1dd09417205a774fa4cf4bfe5657c1d7acb37af1/ldap2pg.yml#L121-L130

**Comment by mignaneB** [comment]
i'll use the one in this example of ldap2pg.yaml : https://github.com/dalibo/ldap2pg/blob/master/ldap2pg.yml#L76

**Comment by mignaneB** [comment]
> @mignaneB yep :
> 
> https://github.com/dalibo/ldap2pg/blob/1dd09417205a774fa4cf4bfe5657c1d7acb37af1/ldap2pg.yml#L121-L130

thanks let me try and tell you

**Comment by mignaneB** [comment]
i still have Empty synchronization map! i think it might be with the query on my ldap

**Comment by bersace** [comment]
@mignaneB *Emtpy synchronization map* is raised before doing any ldap queries. Please share your `ldap2pg.yml`.

**Comment by mignaneB** [comment]
sorry for that very last respone: 
here is my ldap2pg.yml 
`verbosity: 5

postgres:
  # Scope the database where to purge objects when dropping roles. This is the
  # scope of grant on `__all__` databases.
  databases_query: [postgres, appdb, olddb]
  # List of managed schema. This skip pg_toast, pg_temp1, etc. but not pg_catalog.
  schemas_query: |
    SELECT nspname FROM pg_catalog.pg_namespace
    WHERE nspname = 'pg_catalog' OR nspname NOT LIKE 'pg_%'
  # Return managed roles which can be dropped or revoked.
  managed_roles_query: |
    SELECT 'public'
    UNION
    SELECT DISTINCT role.rolname
    FROM pg_roles AS role
    LEFT OUTER JOIN pg_auth_members AS ms ON ms.member = role.oid
    LEFT OUTER JOIN pg_roles AS ldap_roles
      ON ldap_roles.rolname = 'ldap_roles' AND ldap_roles.oid = ms.roleid
    WHERE role.rolname IN ('ldap_roles', 'readers', 'writers', 'owners')
        OR ldap_roles.oid IS NOT NULL
    ORDER BY 1;
  # Since readers/writer/owners groups are globals, we have a global
  # owners_query.
  owners_query: |
    SELECT DISTINCT role.rolname
    FROM pg_catalog.pg_roles AS role
    JOIN pg_catalog.pg_auth_members AS ms ON ms.member = role.oid
    JOIN pg_catalog.pg_roles AS owners
      ON owners.rolname = 'owners' AND owners.oid = ms.roleid
    ORDER BY 1;
privileges:
  # Define an privilege group `ro` with read-only grants
  ro:
  - __connect__
  - __execute__
  - __select_on_tables__
  - __select_on_sequences__
  - __usage_on_schemas__
  - __usage_on_types__

  # `rw` privilege group lists write-only grants
  rw:
  - __temporary__
  - __all_on_tables__
  - __all_on_sequences__

  # `ddl` privilege group lists DDL only grants.
  ddl:
  - __create_on_schemas__


sync_map:
# First, setup static roles and grants
- roles:
  - names:
    - ldap_roles
    - readers
    options: NOLOGIN
    comment: Custom static comment.
  - name: writers
    # Grant reading to writers
    parent: readers
    options: NOLOGIN
  - name: owners
    # Grant read/write to owners
    parent: writers
    options: NOLOGIN
  # Now grant privileges to each groups
  grant:
  - privilege: ro
    role: readers
    # Let's everyone see pg_catalog
    schema: __all__
  - privilege: rw
    role: writers
    # But avoid writers to write in pg_catalog
    schema: public
  # Allow ddl to create tables in public only
  - privilege: ddl
    role: owners
    schema: public
  # owners must have write access to pg_catalog
  - privilege: rw
    role: owners
    schema: pg_catalog
  # Grants on specific schema appdb.appns:
  - privilege: rw
    role: writers
    database: appdb
    schema: appns
  - privilege: ddl
    role: owners
    database: appdb
    schema: appns
ldap:
  uri: ldap://127.0.0.1
  user: admin
  password: "passer"
- ldap:
    base: cn=dba,ou=nss,dc=scytalelabs,dc=com
    filter: '(cn=dba)'
  roles:
  - name: "{cn}"
    options: SUPERUSER LOGIN
    parent:
    - ldap_roles
    - owners
    comment: "Custom comment from LDAP: {dn}"
- ldap:
    base: ou=nss,dc=scytalelabs,dc=com
    filter: "(cn=agent)"
    on_unexpected_dn: warn
  role:
    name: '{member.cn}'
    options: LOGIN
    parent:
    - ldap_roles
    - writers
    comment: 'From {dn}'
- ldap:
    base: ou=nss,dc=scytalelabs,dc=com
    filter: |
      (&
        (cn=bi)
        (objectClass=*)
      )
  role:
    name: '{member.cn}'
    options: LOGIN
    parent:
    - ldap_roles
    - readers`

**Comment by bersace** [comment]
Thanks @mignaneB . Could you please share full verbose output of ldap2pg ?

``` console
$ ldap2pg --verbose
```

**Comment by mignaneB** [comment]
sure here is it :
postgres@ubuntu:~$ ldap2pg --verbose
[ldap2pg.config        INFO] Starting ldap2pg 5.2.
[ldap2pg.config       DEBUG] Trying ./ldap2pg.yml.
[ldap2pg.config       DEBUG] Trying /var/lib/postgresql/.config/ldap2pg.yml.
[ldap2pg.config       DEBUG] Trying /etc/ldap2pg.yml.
[ldap2pg.config       DEBUG] No configuration file found.
[ldap2pg.config       DEBUG] Read verbosity from argv.
[ldap2pg.config       DEBUG] Drop unused hidden privilege __connect__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __create_on_schemas__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_delete_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_execute_on_functions__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_insert_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_references_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_select_on_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_select_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_trigger_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_truncate_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_update_on_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_update_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_usage_on_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_usage_on_types__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __delete_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __execute_on_all_functions__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __global_default_execute_on_functions__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __insert_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __references_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __select_on_all_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __select_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __temporary__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __trigger_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __truncate_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __update_on_all_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __update_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __usage_on_all_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __usage_on_schemas__
[ldap2pg.config       DEBUG] Configuration loaded.
[ldap2pg.config       WARNI] Empty synchronization map!
[ldap2pg.script       WARNI] Running in dry mode. Postgres will be untouched.
[ldap2pg.psql         DEBUG] Connecting to Postgres libpq default.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] SELECT array_agg(attrs.attname)
[ldap2pg.psql         DEBUG] FROM pg_catalog.pg_namespace AS nsp
[ldap2pg.psql         DEBUG] JOIN pg_catalog.pg_class AS tables
[ldap2pg.psql         DEBUG]   ON tables.relnamespace = nsp.oid AND tables.relname = 'pg_authid'
[ldap2pg.psql         DEBUG] JOIN pg_catalog.pg_attribute AS attrs
[ldap2pg.psql         DEBUG]   ON attrs.attrelid = tables.oid AND attrs.attname LIKE 'rol%'
[ldap2pg.psql         DEBUG] WHERE nsp.nspname = 'pg_catalog'
[ldap2pg.psql         DEBUG] ORDER BY 1
[ldap2pg.role         DEBUG] Postgres server supports role options BYPASSRLS, LOGIN, CREATEDB, CREATEROLE, INHERIT, REPLICATION, SUPERUSER.
[ldap2pg.manager       INFO] Inspecting roles in Postgres cluster...
[ldap2pg.psql         DEBUG] Using Postgres connection to libpq default.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] SELECT current_user, rolsuper
[ldap2pg.psql         DEBUG] FROM pg_catalog.pg_roles
[ldap2pg.psql         DEBUG] WHERE rolname = current_user;
[ldap2pg.psql         DEBUG] Using Postgres connection to libpq default.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] SELECT datname FROM pg_catalog.pg_database
[ldap2pg.psql         DEBUG] WHERE datallowconn IS TRUE ORDER BY 1;
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] SELECT
[ldap2pg.psql         DEBUG]   role.rolname, array_agg(members.rolname) AS members,
[ldap2pg.psql         DEBUG]   role.rolbypassrls, role.rolcanlogin, role.rolcreatedb, role.rolcreaterole, role.rolinherit, role.rolreplication, role.rolsuper,
[ldap2pg.psql         DEBUG]   pg_catalog.shobj_description(role.oid, 'pg_authid') as comment
[ldap2pg.psql         DEBUG] FROM
[ldap2pg.psql         DEBUG]   pg_catalog.pg_roles AS role
[ldap2pg.psql         DEBUG] LEFT JOIN pg_catalog.pg_auth_members ON roleid = role.oid
[ldap2pg.psql         DEBUG] LEFT JOIN pg_catalog.pg_roles AS members ON members.oid = member
[ldap2pg.psql         DEBUG] GROUP BY role.rolname, role.rolbypassrls, role.rolcanlogin, role.rolcreatedb, role.rolcreaterole, role.rolinherit, role.rolreplication, role.rolsuper, comment
[ldap2pg.psql         DEBUG] ORDER BY 1;
[ldap2pg.inspector    DEBUG] Ignoring role 'postgres'. Matches 'postgres'.
[ldap2pg.manager      DEBUG] Postgres roles inspection done.
[ldap2pg.manager      DEBUG] LDAP inspection completed. Post processing.
[ldap2pg.manager      DEBUG] No privileges defined. Skipping GRANT and REVOKE.
[ldap2pg.manager       INFO] Nothing to do.
[ldap2pg.script        INFO] Comparison complete.
[ldap2pg.script       DEBUG] Inspecting Postgres took 0:00:00.012770.
[ldap2pg.script       DEBUG] Synchronizing Postgres took 0:00:00.
[ldap2pg.script       DEBUG] Used up to 33.4MiB of memory.
[ldap2pg.psql         DEBUG] Closing Postgres connexion to libpq default.

**Comment by bersace** [comment]
ldap2pg does not find your file :

**Comment by mignaneB** [comment]
my ldap2pg.yml is in /root. Is there a way to indicate the path to yml file to ldap2pg ?

**Comment by bersace** [comment]
@mignaneB yes with `--config` see ldap2pg --help.

**Comment by mignaneB** [comment]
So i moved my yml file into /etc and try it again and i've got:
Failed to read configuration: [Errno 13] Permission denied: '/etc/ldap2pg.yml'
so i made a chmod 777 and run again
Starting ldap2pg 5.2.
Using /etc/ldap2pg.yml.
YAML error with /etc/ldap2pg.yml: while parsing a block mapping
  in "/etc/ldap2pg.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/etc/ldap2pg.yml", line 8, column 3

now i have some syntax error to see i looking at it now

**Comment by bersace** [comment]
@mignaneB Would you mind to post full output of `ldap2pg --version` ?

**Comment by mignaneB** [comment]
yes sure :

ldap2pg 5.2
psycopg2 2.8.5 (dt dec pq3 ext lo64)
python-ldap 3.2.0
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609]

**Comment by bersace** [comment]
Why is the ldap section somewhere in the middle of the sync_map list ? Line 93.

The overral structure of ldap2pg.yml should be:

```
postgres:
  ...

ldap:
  ...

sync_map:
- ...
- ...
```

**Comment by mignaneB** [comment]
i use this example of ldap2gp.yml https://github.com/dalibo/ldap2pg/blob/master/ldap2pg.yml#L76

**Comment by bersace** [comment]
@mignaneB Here is the diff between master and your config :

``` diff
--- ldap2pg.yml	2020-04-03 14:09:40.793163660 +0200
+++ my-mignaneB.yml	2020-05-07 15:29:19.670965838 +0200
@@ -1,23 +1,3 @@
-#
-# **LDAP2PG SAMPLE CONFIGURATION**
-#
-# This is a sample starting point configuration file for ldap2pg.yml. Including
-# static roles, groups, privilege and LDAP query.
-#
-# This configuration assumes the following principles:
-#
-# - All LDAP users are grouped in `ldap_roles` group.
-# - Read privileges are granted to `readers` group.
-# - Write privileges are granted to `writers` group.
-# - DDL privileges are granted to `owners` group.
-# - We have one or more databases with public and maybe a schema.
-# - Grants are not specific to a schema. Once you're writer in a database, you
-#   are writer to all schemas in it.
-#
-# Adapt to your needs! See also full documentation on how to configure ldap2pg
-# at https://ldap2pg.readthedocs.io/en/latest/config/.
-#
-
 verbosity: 5
 
 postgres:
@@ -40,7 +20,6 @@
     WHERE role.rolname IN ('ldap_roles', 'readers', 'writers', 'owners')
         OR ldap_roles.oid IS NOT NULL
     ORDER BY 1;
-
   # Since readers/writer/owners groups are globals, we have a global
   # owners_query.
   owners_query: |
@@ -50,8 +29,6 @@
     JOIN pg_catalog.pg_roles AS owners
       ON owners.rolname = 'owners' AND owners.oid = ms.roleid
     ORDER BY 1;
-
-
 privileges:
   # Define an privilege group `ro` with read-only grants
   ro:
@@ -116,21 +93,23 @@
     role: owners
     database: appdb
     schema: appns
-
-# Now query LDAP to create roles and grant them privileges by parenting.
+ldap:
+  uri: ldap://127.0.0.1
+  user: admin
+  password: "passer"
 - ldap:
-    base: ou=groups,dc=ldap,dc=ldap2pg,dc=docker
-    filter: "(cn=dba)"
-  role:
-    name: '{member.cn}'
-    options: LOGIN SUPERUSER
+    base: cn=dba,ou=nss,dc=scytalelabs,dc=com
+    filter: '(cn=dba)'
+  roles:
+  - name: "{cn}"
+    options: SUPERUSER LOGIN
     parent:
     - ldap_roles
     - owners
     comment: "Custom comment from LDAP: {dn}"
 - ldap:
-    base: ou=groups,dc=ldap,dc=ldap2pg,dc=docker
-    filter: "(cn=app*)"
+    base: ou=nss,dc=scytalelabs,dc=com
+    filter: "(cn=agent)"
     on_unexpected_dn: warn
   role:
     name: '{member.cn}'
@@ -140,7 +119,7 @@
     - writers
     comment: 'From {dn}'
 - ldap:
-    base: ou=groups,dc=ldap,dc=ldap2pg,dc=docker
+    base: ou=nss,dc=scytalelabs,dc=com
     filter: |
       (&
         (cn=bi)
```

The invalid section is

``` diff
--- ldap2pg.yml	2020-04-03 14:09:40.793163660 +0200
+++ my-mignaneB.yml	2020-05-07 15:29:19.670965838 +0200
@@ -1,23 +1,3 @@

+ldap:
+  uri: ldap://127.0.0.1
+  user: admin
+  password: "passer"
 - ldap:
```

This section must be **above** `sync_map:`

**Comment by bersace** [comment]
@mignaneB Do you have some updates on this ?

**Comment by mignaneB** [comment]
sorry i've been very busy:
here is it i thnik i respect the good format ?! : 
verbosity: 5

postgres:
  # Scope the database where to purge objects when dropping roles. This is the
  # scope of grant on `__all__` databases.
  databases_query: [postgres]
  # List of managed schema. This skip pg_toast, pg_temp1, etc. but not pg_catalog.
  schemas_query: |
    SELECT nspname FROM pg_catalog.pg_namespace
    WHERE nspname = 'pg_catalog' OR nspname NOT LIKE 'pg_%'
  # Return managed roles which can be dropped or revoked.
  managed_roles_query: |
    SELECT 'public'
    UNION
    SELECT DISTINCT role.rolname
    FROM pg_roles AS role
    LEFT OUTER JOIN pg_auth_members AS ms ON ms.member = role.oid
    LEFT OUTER JOIN pg_roles AS ldap_roles
      ON ldap_roles.rolname = 'ldap_roles' AND ldap_roles.oid = ms.roleid
    WHERE role.rolname IN ('ldap_roles', 'readers', 'writers', 'owners')
        OR ldap_roles.oid IS NOT NULL
    ORDER BY 1;
  # Since readers/writer/owners groups are globals, we have a global
  # owners_query.
  owners_query: |
    SELECT DISTINCT role.rolname
    FROM pg_catalog.pg_roles AS role
    JOIN pg_catalog.pg_auth_members AS ms ON ms.member = role.oid
    JOIN pg_catalog.pg_roles AS owners
      ON owners.rolname = 'owners' AND owners.oid = ms.roleid
    ORDER BY 1;

ldap:
  uri: ldap://192.168.1.19
  user: admin
  password: "passer"

ldap:
    base: cn=dba,ou=nss,dc=scytalelabs,dc=com
    filter: "(cn=dba)"
  roles:
  - name: "{cn}"
    options: SUPERUSER LOGIN
    parent:
    - ldap_roles
    - owners
    comment: "Custom comment from LDAP: {dn}"
ldap:
    base: ou=nss,dc=scytalelabs,dc=com
    filter: "(cn=agent)"
    on_unexpected_dn: warn
  role:
    name: "{member.cn}"
    options: LOGIN
    parent:
    - ldap_roles
    - writers
    comment: "From {dn}"
ldap:
    base: ou=nss,dc=scytalelabs,dc=com
    filter: |
      (&
        (cn=bi)
        (objectClass=*)
      )
  role:
    name: "{member.cn}"
    options: LOGIN
    parent:
    - ldap_roles
    - readers

privileges:
  # Define an privilege group `ro` with read-only grants
  ro:
  - __connect__
  - __execute__
  - __select_on_tables__
  - __select_on_sequences__
  - __usage_on_schemas__
  - __usage_on_types__

  # `rw` privilege group lists write-only grants
  rw:
  - __temporary__
  - __all_on_tables__
  - __all_on_sequences__

  # `ddl` privilege group lists DDL only grants.
  ddl:
  - __create_on_schemas__



sync_map:
# First, setup static roles and grants
- roles:
  - names:
    - ldap_roles
    - readers
    options: NOLOGIN
    comment: Custom static comment.
  - name: writers
    # Grant reading to writers
    parent: readers
    options: NOLOGIN
  - name: owners
    # Grant read/write to owners
    parent: writers
    options: NOLOGIN
  # Now grant privileges to each groups
  grant:
  - privilege: ro
    role: readers
    # Let's everyone see pg_catalog
    schema: __all__
  - privilege: rw
    role: writers
    # But avoid writers to write in pg_catalog
    schema: public
  # Allow ddl to create tables in public only
  - privilege: ddl
    role: owners
    schema: public
  # owners must have write access to pg_catalog
  - privilege: rw
    role: owners
    schema: pg_catalog
  # Grants on specific schema appdb.appns:
  - privilege: rw
    role: writers
    database: appdb
    schema: appns
  - privilege: ddl
    role: owners
    database: appdb
    schema: appns

when i run ldap2pg i got : 
YAML error with /etc/ldap2pg.yml: while parsing a block mapping
  in "/etc/ldap2pg.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/etc/ldap2pg.yml", line 41, column 3

**Comment by bersace** [comment]
@mignaneB you still have multiple ldap entries before sync_map. Here is the yaml structure, with spaces shown as ¬ for the sake of precision :

``` yaml
postgres:
¬¬databases_query: ...

ldap:  # LDAP connexion parameters, not query !
¬¬user: ...

# NO OTHER ldap: at colum 0.

sync_map:
- ldap:  # THIS IS AN LDAP QUERY, bellow `sync_map` and prefixed with hyphen
¬¬¬¬base: ...
¬¬role: ...
- ldap:  # another query
¬¬¬¬base: ...
¬¬role: ...
```

**Comment by mignaneB** [comment]
ok i see i'll feedback when i correct my file

**Comment by bersace** [comment]
Closing. Please reopen if updates. :gift:
