### ISSUE TITLE
Recursive LDAP queries

### ISSUE THREAD

**Issue by kawehk89** [dalibo/ldap2pg#348]
We are currently evaluating ldap2pg for synchronizing database users (Postgres roles which are meant to log in and receive specific privilege sets based on parent roles, under which those (user-)roles should be created). We love ldap2pg so far, but have a use case / requirement which we have not been able to determine do-ability via ldap2pg.

We would like to achieve the following:

- We’d require to define static roles granted static sets of privilege sets (do-able via ldap2pg)
- Then, we’d require to resolve specific users in a recursive manner, through nested LDAP groups, e.g.:
  - Group A, objectClass is known, e.g. `Group`
    - Group B is member of Group A, objectClass is known, e.g. `Group`
      - n users are part of Group C, objectClass is known, e.g. `Person`
      - Group C is member of Group B, objectClass is known, e.g. `Group`
        - k users are part of Group C, objectClass is known, e.g. `Person`

The desired outcome would be:
- Via group A, `n+k` users should be created as Postgres roles under `1..n` static parent groups- Groups A, B and C should not be created as Postgres roles.

Is there a way for us to achieve this via `ldap2pg`? We found following cookbook https://ldap2pg.readthedocs.io/en/latest/cookbook/ and attempted utilizing what is described in that context (joins, which would result in additional LDAP queries based on the nested group structure), but haven’t been able to achieve our required result.

We have achieved the required result by defining less restricted LDAP base queries, and then filtering for the actual users via an `isMemberOf` filter; that however pushes the load onto LDAP and would result in too heavy queries.

Is there a way for us to configure `ldap2pg` in such a manner, that nested group structures as described above are recursively queried, resulting all users found in those nested groups to be created as according Postgres roles?

Merci beaucoup à l'avance!

Kaweh

**Comment by bizen-ya** [comment]
Hello Kaweh,

You can try with AD extensions: 

- description: "Query LDAP to create superusers."
  ldap:
    base: "OU=Groups,OU=xxxxxxx,OU=xxxxxxxxx,DC=xxxxxxxx,DC=xxxxxxxx,DC=xxxxxxxx"
    filter: "(|(memberOf:1.2.840.113556.1.4.1941:=CN=<Group name>,OU=Groups,OU=xxxxxxxxx,OU=xxxxxxx,DC=xxxxxxx,DC=xxxxxxx,DC=xxxxxx))"
    on_unexpected_dn: warn
  role:
    # LDAP attribute member is a Distinguished Name. Use CN component of the
    # member value.
    name: '{member.cn}'
    options: LOGIN SUPERUSER
    parent:
    - ldap_roles
    comment: "From LDAP group {dn}"

**Comment by bersace** [comment]
Hi @kawehk89 . As of now, ldap2pg only supports one level of sub-query for *all* values of an attributes.

Do you mix Group and Person entities in the same attribute ?

**Comment by bersace** [comment]
Stale. Please reopen if updates.

**Comment by seanzechman** [comment]
We have nested groups - wondering if newer version of ldap2pg supports using a nested ldap group to create roles
