### ISSUE TITLE
Use STARTTLS when connecting to ldap server

### ISSUE THREAD

**Issue by mgiritli** [dalibo/ldap2pg#349]
I was wondering if ldap2pg supports connecting to LDAP servers using STARTTLS (instead of ldaps)? I could not find any configuration options mentioned in the documentation.

**Comment by bersace** [comment]
Hi @mgiritli, thanks for reaching !

You should configure starttls with regular ldaprc file.

**Comment by bersace** [comment]
Closing. Please reopen if you have updates.
