### ISSUE TITLE
LDAPCONF and LDAPRC not taken in account

### ISSUE THREAD

**Issue by bizen-ya** [dalibo/ldap2pg#350]
## ldap2pg.yml

-- je ne pense pas que cela soit utile, problème rencontré sur la CLI.

## Expectations

Le fichier de config openldap n'est pas sourcé par défaut, je tente de le charger avec $LDAPCONF 

LDAPCONF=/etc/openldap/ldap.conf ldap2pg -c ${MYDIR}/files/ldap2pg.yml --real

## Verbose output of ldap2pg execution
Fichier non chargé, mais on voit bien que la variable est prise en compte : 

<details><summary>Verbose output</summary><pre>

[ldap2pg.config       DEBUG] Configuration loaded.
[ldap2pg.script       DEBUG] Setting up LDAP client.
[ldap2pg.ldap         DEBUG] Ignoring: [Errno 2] No such file or directory: u'/etc/ldap/ldap.conf'
[ldap2pg.ldap         DEBUG] Ignoring: [Errno 2] No such file or directory: u'/local/home/xxxxxx/ldaprc'
[ldap2pg.ldap         DEBUG] Ignoring: [Errno 2] No such file or directory: u'/local/home/xxxxxx/.ldaprc'
[ldap2pg.ldap         DEBUG] Ignoring: [Errno 2] No such file or directory: u'/xxxx/xxxxxxxx/ldaprc'
**[ldap2pg.ldap         DEBUG] Read CONF from env.**
[ldap2pg.ldap         DEBUG] Read SASL_MECH from env.
[ldap2pg.ldap         DEBUG] Connecting to LDAP server ldap://:389.

</pre></details>

Dans le code, les fichier pointés par $LDAPCONF sont chargés -avant- la récupération de l'environnement : 

    if 'NOINIT' in environ:
        logger.debug("LDAPNOINIT defined. Disabled ldap.conf loading.")
    else:
        for e in read_files(conf='/etc/ldap/ldap.conf', rc='ldaprc'):
            logger.debug('Read %s from %s.', e.option, e.filename)
            options.set_raw(e.option, e.value)
        for e in read_files(conf=options.get('CONF'), rc=options.get('RC')):
            logger.debug('Read %s from %s.', e.option, e.filename)
            options.set_raw(e.option, e.value)
        for option, value in environ.items():
            logger.debug('Read %s from env.', option)
            options.set_raw(option, value)

plus généralement, le chargement par défaut du fichier /etc/openldap/ldap.conf serait utile.

**Comment by bersace** [comment]
Salut @bizen-ya , merci pour le retour.

J'ai un doute sur le problème. J'ai l'impression qu'il y en a deux.

1. le fichier '/etc/openldap/ldap.conf' n'est pas recherché par défaut.
2. Le fichier indiqué par `LDAPCONF` n'est pas chargé.

Peux-tu me confirmer ces deux problèmes ou l'un des deux ?

**Comment by bizen-ya** [comment]
Bonjour @bersace ,

Effectivement j'aurais peut être du ouvrir deux case séparés

J'ai eux le premier problème ( corigé #358 , merci :) ) , et suis tombé sur le second en essayant de contourner le premier.

**Comment by bersace** [comment]
Released in ldap2pg 5.6 \o/
