### ISSUE TITLE
Reassign fail when dbowner has '-' in it's name

### ISSUE THREAD

**Issue by bizen-ya** [dalibo/ldap2pg#353]
When an user is removed from the group, ldap2pg try to reassign the objects, but the target user has '-' in his name

Problem 1 : The reassign fail
Problem 2 : The target user is current session , not db owner.

## Expectations

Réassign objects to the dbowner user

## Verbose output of ldap2pg execution

<details><summary>Verbose output</summary>

Starting ldap2pg 5.5.
Using /tmp/tmp.aHnoG9A71R.
Running in real mode.
Inspecting roles in Postgres cluster...
Setup static roles and grants.
Query LDAP to create superusers.
Querying LDAP OU=Groups,OU=I0200,OU=Co... (|)...
Delete spurious ldap_roles members.
Reassign XX-XXXX-XXXXX objects and purge ACL on xxxxxx.
Error while executing SQL query:
syntax error at or near "-"
LINE 1: GRANT "XX-XXXX-XXXXX" TO xx-xxxx-xxxxx
                                      ^
QUERY:  GRANT "XX-XXXX-XXXXX" TO xx-xxxx-xxxxx
CONTEXT:  PL/pgSQL function inline_code_block line 1 at EXECUTE
25/02/21 16:07:49 : Error ldap2pg
 [25/02/2021 16:07.49] ~

</details>

**Comment by bersace** [comment]
Salut, Peux-tu exécuter avec `--verbose` ? Ça permet de voir la requête complète. Merci :+1:

**Comment by bizen-ya** [comment]
J'ai du réduire le log et modifier les champs pour des questions d'anonymisation, désolé 😊 


```
[ldap2pg.psql         CHANG] Delete spurious ldap_roles members.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] REVOKE "ldap_roles" FROM "xx-xxxxx-xxx-tst";
[ldap2pg.psql         DEBUG] Connecting to Postgres dbname=dbnamexxxxx.
[ldap2pg.psql         CHANG] Reassign xx-xxxxx-xxx-tst objects and purge ACL on dbnamexxxxx.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] DO $$BEGIN EXECUTE 'GRANT "xx-xxxxx-xxx-tst" TO '||SESSION_USER; END$$;
[ldap2pg.psql         DEBUG] DO $$BEGIN EXECUTE 'REASSIGN OWNED BY "xx-xxxxx-xxx-tst" TO '||SESSION_USER; END$$;
[ldap2pg.psql         DEBUG] DROP OWNED BY "xx-xxxxx-xxx-tst";
[ldap2pg.script       CRITI] Error while executing SQL query:
[ldap2pg.script       CRITI] syntax error at or near "-"
[ldap2pg.script       CRITI] LINE 1: GRANT "xx-xxxxx-xxx-tst" TO xx-xxxx-xxxx-xxxx
[ldap2pg.script       CRITI]                                       ^
[ldap2pg.script       CRITI] QUERY:  GRANT "xx-xxxxx-xxx-tst" TO xx-xxxx-xxxx-xxxx
[ldap2pg.script       CRITI] CONTEXT:  PL/pgSQL function inline_code_block line 1 at EXECUTE
[ldap2pg.psql         DEBUG] Closing Postgres connexion to libpq default.
[ldap2pg.psql         DEBUG] Closing Postgres connexion to dbname=dbnamexxxxx.
```

**Comment by bizen-ya** [comment]
super 👍 

Le fait de réassigner au SESSION_USER , et non pas au databaseowner , c'est voulu ?

**Comment by bersace** [comment]
@bizen-ya c'est le premier choix qui est venu et toutes propositions est bienvenue :-) Je suggère d'ouvrir un autre ticket pour suivre l'évolution du code pour assigner au database owner.

**Comment by bersace** [comment]
Corrigé dans ldap2pg 5.6
