### ISSUE TITLE
ldap2pg without kerberos

### ISSUE THREAD

**Issue by mtherio** [dalibo/ldap2pg#367]
In our organization, the security team does not want to use Kerberos. This approach cause me problem when I try to run a ldapsearch with SASL. I receive this error message: 

ldap_sasl_interactive_bind_s: Local error (-2)
        additional info: SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (No Kerberos credentials available (default cache: KEYRING:persistent:3646))

Could we use SASL without Kerberos?
Thanks

**Comment by bersace** [comment]
Hi @mtherio , thanks for reaching.

Configure ldapsearch through ldaprc file and ldap2pg should work too. ldap2pg uses the same library as ldapsearch, ldapwhoami and other ldap utils. See ldap.conf(1) and `SASL_MECH` option.

Regards,
Étienne

**Comment by bersace** [comment]
Stale. Please reopen if you have updates.
