### ISSUE TITLE
Difference in connecting to LDAP server with version 5.5 and 5.6

### ISSUE THREAD

**Issue by HermanPool** [dalibo/ldap2pg#372]
I get a difference in connecting to my LDAP server with ldap2pg version 5.5 and 5.6
In version 5.5 everything goes well.

With version 5.5, I see in the log file:
Connecting to LDAP server ldaps://ldapserver.lan
Trying simple bind.
Doing: ldapwhoami -x -D CN=......................
Running in dry mode. Postgres will be untouched
Connecting to Postgres libpq default.

In version 5.6, I see in the log file:
Connecting to LDAP server ldaps://ldapserver.lan
Trying SASL GSSAPI auth.
Doing: ldapwhoami -Y GSSAPI
Failed to connect to LDAP: {'info': SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure. Minor code may provide more information (No Kerberos credentials available (default cache: KEYRING:persistent:512))', 'desc': 'Local error'}

Why is version 5.6 trying with "SASL GSSAPI auth" and 5.5 with "simple bind"?
What is wrong and how can I solve this issue?

With regards,

Herman Pool

**Comment by bersace** [comment]
Hi @HermanPool , thanks for reaching.

After the changelog at https://ldap2pg.readthedocs.io/en/latest/changelog/#ldap2pg-56, I guess that you have something in `/etc/openldap/ldap.conf`. What tells ldap2pg --verbose about this ?

Regards

**Comment by bersace** [comment]
Closing stale issue.
