### ISSUE TITLE
Crash on bad syntax in ldaprc

### ISSUE THREAD

**Issue by lakdahoo** [dalibo/ldap2pg#373]
## What do you want?
How we can configure the ldap2pg.yml with nested group for finding users in incursive groups

I want to configure ldap2pg.yml for synchronising between ldap and postgres database. maybe i misunderstood how to configure it.

## ldap2pg.yml

<details><summary>ldap2pg.yml</summary>
sync_map:
# A single static roles
- role:
   name: GL-DBI-DIS-PROD-RW
   options: NOLOGIN
- ldap:
   base: "(&(objectClass=user)(memberOf:1.2.840.113556.1.4.1941:=CN=GL-DBI-DIS-PROD-RW,OU=DBA,OU=Ressources,OU=Groupes,OU=Moche comme tout,DC=Paris,DC=lan)"
   filter: "objectClass=groupOfNames)"
  roles:
   name: '{cn}'
   options: LOGIN
   parent: GL-DBI-DIS-PROD-RW
</details>

in the logfile i've got this error:

```
Unhandled error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ldap2pg/script.py", line 94, in main
    exit(wrapped_main(config))
  File "/usr/local/lib/python3.6/site-packages/ldap2pg/script.py", line 34, in wrapped_main
    ldapconn = ldap.connect(**config['ldap'])
  File "/usr/local/lib/python3.6/site-packages/ldap2pg/ldap.py", line 276, in connect
    options = gather_options(**kw)
  File "/usr/local/lib/python3.6/site-packages/ldap2pg/ldap.py", line 360, in gather_options
    for e in read_files(conf='/etc/ldap/ldap.conf', rc='ldaprc'):
  File "/usr/local/lib/python3.6/site-packages/ldap2pg/ldap.py", line 403, in read_files
    for entry in parserc(fo):
  File "/usr/local/lib/python3.6/site-packages/ldap2pg/ldap.py", line 423, in parserc
    option, value = line.split(None, 1)
ValueError: not enough values to unpack (expected 2, got 1)
Please file an issue at https://github.com/dalibo/ldap2pg/issues with full log.
```

Thank you for your help.
Lak

**Comment by bersace** [comment]
Hi @lakdahoo, thanks for reaching !

It looks like ldap2pg didn't hit an unexpected syntax in an ldaprc file. Could share a verbose output and a redacted version of your ldaprc files ?

Regards,
Étienne

**Comment by lakdahoo** [comment]
Hi,

Thank you for your answer.

I already resolved my issue.

Regards.
Lak

Le lun. 9 août 2021 à 11:12, Étienne BERSAC ***@***.***> a
écrit :

**Comment by bersace** [comment]
Hi @lakdahoo. Can you still share with me the bad line so that ldap2pg could produce a meaning full message ?

Regards
