### ISSUE TITLE
LDAP_PORT overrides LDAPPORT

### ISSUE THREAD

**Issue by jeanpommier** [dalibo/ldap2pg#374]
## What do you want?
Properly configure the LDAP

## details

Hi,
I'm using the dalibo/ldap2pg:5.5 docker image with the [config file provided in the doc](https://raw.githubusercontent.com/dalibo/ldap2pg/master/ldap2pg.yml). For now, I'm just trying the connection parameters, using the environment variables, 

`PGDSN=postgresql://georchestra:super_secret_password@postgis-user/georchestra LDAPURI=ldap://ldap LDAPBINDDN=cn=admin,dc=georchestra,dc=org LDAPPASSWORD=ldap_super_secret_password ldap2pg -n
`
I'm getting a cryptic error:
```
Starting ldap2pg 5.5.
    Using /workspace/ldap2pg.yml.
    Unhandled error:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/dist-packages/ldap2pg/script.py", line 94, in main
        exit(wrapped_main(config))
      File "/usr/local/lib/python3.7/dist-packages/ldap2pg/script.py", line 34, in wrapped_main
        ldapconn = ldap.connect(**config['ldap'])
      File "/usr/local/lib/python3.7/dist-packages/ldap2pg/ldap.py", line 276, in connect
        options = gather_options(**kw)
      File "/usr/local/lib/python3.7/dist-packages/ldap2pg/ldap.py", line 377, in gather_options
        options.set_raw(k, v)
      File "/usr/local/lib/python3.7/dist-packages/ldap2pg/ldap.py", line 318, in set_raw
        value = parser(raw)
    ValueError: invalid literal for int() with base 10: 'tcp://10.43.1.145:389'
    Please file an issue at https://github.com/dalibo/ldap2pg/issues with full log.
```
I suppose I did something wrong, although I feel it complies with the documentation. Have I missed something here ?
Thanks,
Best,
Jean

**Comment by bersace** [comment]
Salut, peux-tu partager les messages verbeux ?

**Comment by jeanpommier** [comment]
Oh, yes, sorry:
```
[ldap2pg.config        INFO] Starting ldap2pg 5.5.
[ldap2pg.config       DEBUG] Trying ./ldap2pg.yml.
[ldap2pg.config        INFO] Using /workspace/ldap2pg.yml.
[ldap2pg.config       DEBUG] Read dry from argv.
[ldap2pg.config       DEBUG] Read verbosity from argv.
[ldap2pg.config       DEBUG] Read ldap:uri from LDAPURI.
[ldap2pg.config       DEBUG] Read ldap:port from LDAP_PORT.
[ldap2pg.config       DEBUG] Read ldap:binddn from LDAPBINDDN.
[ldap2pg.config       DEBUG] Read ldap:password from LDAPPASSWORD.
[ldap2pg.config       DEBUG] Read postgres:dsn from PGDSN.
[ldap2pg.config       DEBUG] Read postgres:owners_query from YAML.
[ldap2pg.config       DEBUG] Read postgres:managed_roles_query from YAML.
[ldap2pg.config       DEBUG] Read postgres:schemas_query from YAML.
[ldap2pg.config       DEBUG] Read privileges from YAML.
[ldap2pg.config       DEBUG] Read sync_map from YAML.
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_execute_on_functions__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __execute_on_all_functions__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __global_default_execute_on_functions__
[ldap2pg.config       DEBUG] Configuration loaded.
[ldap2pg.script       DEBUG] Setting up LDAP client.
[ldap2pg.ldap         DEBUG] Found rcfile /etc/ldap/ldap.conf.
[ldap2pg.ldap         DEBUG] Read TLS_CACERT from /etc/ldap/ldap.conf.
[ldap2pg.ldap         DEBUG] Ignoring: [Errno 2] No such file or directory: '/root/ldaprc'
[ldap2pg.ldap         DEBUG] Ignoring: [Errno 2] No such file or directory: '/root/.ldaprc'
[ldap2pg.ldap         DEBUG] Ignoring: [Errno 2] No such file or directory: '/workspace/ldaprc'
[ldap2pg.ldap         DEBUG] Read URI from env.
[ldap2pg.ldap         DEBUG] Read PASSWORD from env.
[ldap2pg.ldap         DEBUG] Read BINDDN from env.
[ldap2pg.ldap         DEBUG] Read URI from YAML.
[ldap2pg.ldap         DEBUG] Read PORT from YAML.
[ldap2pg.script       ERROR] Unhandled error:
[ldap2pg.script       ERROR] Traceback (most recent call last):
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.7/dist-packages/ldap2pg/script.py", line 94, in main
[ldap2pg.script       ERROR]     exit(wrapped_main(config))
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.7/dist-packages/ldap2pg/script.py", line 34, in wrapped_main
[ldap2pg.script       ERROR]     ldapconn = ldap.connect(**config['ldap'])
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.7/dist-packages/ldap2pg/ldap.py", line 276, in connect
[ldap2pg.script       ERROR]     options = gather_options(**kw)
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.7/dist-packages/ldap2pg/ldap.py", line 377, in gather_options
[ldap2pg.script       ERROR]     options.set_raw(k, v)
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.7/dist-packages/ldap2pg/ldap.py", line 318, in set_raw
[ldap2pg.script       ERROR]     value = parser(raw)
[ldap2pg.script       ERROR] ValueError: invalid literal for int() with base 10: 'tcp://10.43.1.145:389'
[ldap2pg.script       ERROR] Please file an issue at https://github.com/dalibo/ldap2pg/issues with full log.
```
BTW, using the ldap2pg client from my computer (with some port forwarding to access the remote DB & LDAP) works. It's when I try to run it from a docker image on my infra that it give this error message: maybe the docker image is damaged/not up-to-date ?
Thanks

**Comment by bersace** [comment]
Looks like you have a `LDAP_PORT` env var that contains `tcp://10.43.1.145:389`. What does docker inspect shows ?

**Comment by jeanpommier** [comment]
Yes, this is my LDAP container. It's on Kubernetes, so not docker. But I have the ldap service opened on port 389, so it should work.
![image](https://user-images.githubusercontent.com/4491521/131333789-152085f8-66ea-4829-8d42-47a532515e75.png)

**Comment by bersace** [comment]
@jeanpommier What is generating `LDAP_PORT=tcp://10.43.1.145:389` ? It should be `LDAPPORT=389` with single integer and without underscore. see ldap.conf(5).

**Comment by jeanpommier** [comment]
Good question. I'd say your docker image, since I'm not giving that env var anywhere (and if it were on my side, it would not be reported by ldap2pg, right ?

**Comment by bersace** [comment]
There is no bash script wrapping ldap2pg in the docker image. Maybe is it an env var from kubernetes ? Would be great to inspect the pod for what env vars are sent to the container.

**Comment by jeanpommier** [comment]
mmmh, investigating a bit, I'm finding that same env var in my LDAP container, so it may come from the ldap container.
Which is weird, I'm not declaring it, so it must be an internal env var from this container (generated from [this code](https://github.com/georchestra/georchestra/tree/master/ldap)).

Would it be some legacy ldap config trailing around, that would mess with ldap2pg ?

**Comment by jeanpommier** [comment]
oh, yes, it may also be some auto-generated env var from kubernetes. I'll investigate that tomorrow (can't right now)

Thanks, I'll keep you posted

**Comment by jeanpommier** [comment]
Yes, running printenv, I indeed get that env var in the ldap2pg container. I'll try overriding it, to see what happens

**Comment by jeanpommier** [comment]
OK, overriding the LDAP_PORT env var seems to solve the issue. So I guess that ldap2pg is also looking for that variable, behind the scenes. Unfortunately it seems to take precedence over LDAPPORT variable, but I believe I'll be able to manage.

Thanks for the help !

**Comment by bersace** [comment]
LDAP_PORT is an old feature that I didn't dropped for compatibility reason. I prefer to use regular LDAPPORT from openldap project.
