### ISSUE TITLE
use docker secrets to pass PG and LDAP passwords

### ISSUE THREAD

**Issue by jeanpommier** [dalibo/ldap2pg#380]
Hi,
he postgres docker image, for instance, allows to pass the postgresql password as a docker secret, using the POSTGRES_PASSWORD_FILE environment variable

Do you support something  similar, both for PG and LDAP passwords, in your docker image ?
I can't really figure out where you parse the environment variables (for instance PGPASSWORD)
Thanks

**Comment by bersace** [comment]
Configuration marshalling is implemented in https://github.com/dalibo/ldap2pg/blob/master/ldap2pg/config.py

env var is built from yaml tag name. `color` is mapped to `LDAP2PG_COLOR`. Mapping is declared at https://github.com/dalibo/ldap2pg/blob/master/ldap2pg/config.py#L396 .

PGPASSWORD is a regular libpq env var. ldap2pg does not manage this.

Loading _FILE seems a good idea. It should add a dependency.

**Comment by bersace** [comment]
@jeanpommier , ouaip, je veux bien voir un patch avec la version originale en bash de fileenv dans entrypoint.sh.

**Comment by bersace** [comment]
Fait. Merci @jeanpommier pour le patch initial !
