### ISSUE TITLE
Roles are not getting deleted after the LDAP Group is removed from config

### ISSUE THREAD

**Issue by guruguruguru** [dalibo/ldap2pg#382]
Hi,

I just found out that if i remove a LDAP group from my config, the users/roles that were in this group are not getting removed from postgres.

Logfile says:

> [ldap2pg.inspector    DEBUG] May reuse role 'role1'.
> [ldap2pg.inspector    DEBUG] May reuse role 'role2'.
> [ldap2pg.inspector    DEBUG] May reuse role 'role3'.

I am not sure if I am just missing a setting? Do you have any idea?

Edit/To add: Users that are deleted from a used LDAP group are dropped

Thanks Dennis

**Comment by bersace** [comment]
You're welcome. :+1:
