### ISSUE TITLE
ldap2pg takes a long time on ldapwhoami

### ISSUE THREAD

**Issue by m3nthal** [dalibo/ldap2pg#387]
Hi,

I am using the following version on ldap2pg:
```
ldap2pg 5.6
psycopg2 2.7.7 (dt dec pq3 ext lo64)
python-ldap 3.1.0
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0]
```
connecting to ldap with:
```
ldap:
  uri: ldap://<REDACTED>:389
  binddn: CN=service-account,OU=Service Accounts,DC=domain,DC=local
  password: <REDACTED>
```

when running `ldap2pg --verbose` I get this:
```
[2021-11-15 16:51:27] [ldap2pg.ldap         DEBUG] Connecting to LDAP server ldap://<REDACTED>:389.
[2021-11-15 16:51:27] [ldap2pg.ldap         DEBUG] Trying simple bind.
[2021-11-15 16:51:27] [ldap2pg.ldap         DEBUG] Doing: ldapwhoami -x -D CN=service-account,OU=Service Accounts,DC=domain,DC=local -W
[2021-11-15 16:51:43] [ldap2pg.script       WARNI] Running in dry mode. Postgres will be untouched.
[2021-11-15 16:51:43] [ldap2pg.psql         DEBUG] Connecting to Postgres <REDACTED>.
```

You can see that `ldapwhoami` step takes 16 seconds. When I run the same command manually, it runs under a second.
What could be the issue here?

**Comment by bersace** [comment]
Hi @m3nthal . The log message is misleading. ldap2pg is not **Doing** a ldapwhoami but calling `simple_bind` (see previous message). Can you confirm that following LDAP searches are fast ?

You may have more information with strace or other low level debugger.

**Comment by m3nthal** [comment]
> Hi @m3nthal . The log message is misleading. ldap2pg is not **Doing** a ldapwhoami but calling `simple_bind` (see previous message). Can you confirm that following LDAP searches are fast ?
> 
> You may have more information with strace or other low level debugger.

Hi @bersace, thank you for replying. 
LDAP searches might take a while for sure. I am not good with debugging tools, so if you could give me a hand with debugging commands - will be super helpful. Which LDAP searches does `simple_bind` perform? Maybe I could test them with `ldapsearch` command to compare. Is there any way I can optimise `binddn` to speed up the binding process?

**Comment by bersace** [comment]
Hi @m3nthal ,

`simple_bind` is only the authentication API call. It's done a single time. This is why ldap2pg logs `ldapwhoami` rather than `ldapsearch`. ldap commands logged by ldap2pg are hint to reproduce equivalent action using OpenLDAP utils, but ldap2pg does use libldap directly.

Sometime, I use `strace ldap2pg` to know why it's blocking (Is it DNS ? Network ?). Beware that this produces a lot of messages.

**Comment by m3nthal** [comment]
I think this one could be closed. The root cause was network.

**Comment by bersace** [comment]
@m3nthal , you're welcome. If a better message would help, please suggest :-)
