### ISSUE TITLE
TypeError: query_ldap() got an unexpected keyword argument 'uri'

### ISSUE THREAD

**Issue by diegodblr** [dalibo/ldap2pg#390]
## What do you want?

Hi there! I am trying to use ldap2pg to synchronize my AD in my postgresql. I dont know how to configure the ldap2pg.yml correctly. Can somebody help me?
![image](https://user-images.githubusercontent.com/22057262/142223065-133662e6-ca80-42d6-9dcf-d441145a914d.png)

## ldap2pg.yml

<details><summary>ldap2pg.yml</summary><pre>
postgres:
  dsn: postgres://postgres:postgres@127.0.0.1:5432/

sync_map:
- role:
    name: ldap
    options: NOLOGIN
- ldap:
    uri: ldaps://ad.host.br
    user: svc
    password: "password"
    base: "OU=Intranet,DC=ad,DC=host,DC=br"
    filter: "(sAMAccountName=$username)"
    attribute: cn
  role:
    name_attribute: cn
    options: LOGIN
    parent: ldap

</pre></details>

**Comment by bersace** [comment]
Hi @diegodblr . ldap sections are mixed in ldap2pg.yml. I'm thinking of renaming `ldap` entry in `sync_map` to `ldeapsearch` to distinguish them.

``` yaml

ldap:
  uri: ...

sync_map:
- ldap:
    base: ...
    filter: ...
```

Please keep this issue open as ldap2pg must at least not spit a traceback with such config, and I'll track `ldapsearch` rename here.

**Comment by diegodblr** [comment]
Hi @bersace. Thanks for your help. But i need your help to understand how i configure the ldap2pg.yml to put all users from my active directory in my database postgresql.

**Comment by bersace** [comment]
Hi @diegodblr You make me think of a quickstart documentation. It seems that documentations misses a guide. I'll start by answering your questions here and will eventually end up by writing a propery guide in the documentation. Here is the pitch :

ldap2pg computes from a YAML file an expected configuration or roles and privileges, inspect a PostgreSQL cluster and sync it to match the expectation. The YAML file includes a synchronisation map that describes steps to define the expected configuration using static declaration or dynamic declaration fed by LDAP searches. If ldap2pg drops roles found in PostgreSQL instance that are not defined in expected configuration, same goes for grant. The philosphy is *if it's not explicitly defined, drop*. Each steps contains one or more `role` rule to define roles and `grant` rules to define grants. Each steps with an `ldap` or `ldapsearch` section will trigger an LDAP query est inject LDAP attributes into rules to define new expected roles.

ldap2pg.yml allows you to customize a lot to e.g. synchronize only a subset of roles in a cluster, handle custom privileges, etc.

@diegodblr Does this help you ? Please ask more precise questions.

**Comment by diegodblr** [comment]
Hi @bersace!

I am using the https://raw.githubusercontent.com/dalibo/ldap2pg/master/ldap2pg.yml and now there is no error. I saw that the ldap2pg created new users in the postgresql: ldap, ldap_roles, owners, readers and writers. But no one user from my active directory. I saw that the ldap2pg did not tryied to connect in my ad. When i use ldapsearch -v -x -H ldap://ad.host.com.br -D "CN=svc,OU=Services,OU=Users,OU=Global,DC=host,DC=com,DC=br" -b "OU=Intranet,DC=host,DC=com,DC=br" -W, everything is going well. I dont know what i need to do to fix that.

![image](https://user-images.githubusercontent.com/22057262/142617105-745a6be8-0019-446d-bc48-74d72029d3d9.png)

**Comment by diegodblr** [comment]
I made the upgrade version from the ldap2pg to 5.7 and now it is trying to connect to my active directory, but there are no new users in my postgresql.

![image](https://user-images.githubusercontent.com/22057262/142624158-71155239-2cb6-4a7f-bf54-128dfe82a44b.png)

**Comment by diegodblr** [comment]
@bersace , thanks for your patience. After the upgrade of the ldap2pg is running well. It created all the user in my active directory.

![image](https://user-images.githubusercontent.com/22057262/142630362-8c1c1c98-ad3a-4646-ac18-8421eb44a2a8.png)

**Comment by bersace** [comment]
Hi @diegodblr 

> ![image](https://user-images.githubusercontent.com/22057262/142617105-745a6be8-0019-446d-bc48-74d72029d3d9.png)

You should not define both user (for SASL) and binddn (for simple bind).

I'm not sure whether 5.7 changes anything about querying LDAP. I only update the config handling.

Do you have other questions ?

**Comment by diegodblr** [comment]
All is working fine using ldap, but when i put ldaps there is an error.


![image](https://user-images.githubusercontent.com/22057262/142635623-2933597c-62d3-49bb-8218-9d8a4cb45d5b.png)

**Comment by diegodblr** [comment]
Sorry, i think the error was because the port was wrong.

**Comment by bersace** [comment]
@diegodblr yes. You may use the new startls option in ldap2pg 5.7. The libldap message is not very expressive.

``` yaml
ldap:
  uri: ldap://...
  starttls: yes
  ...
```

**Comment by diegodblr** [comment]
Hi @bersace !

How can i authorize a user from my active directory in an specific database and schema?

**Comment by diegodblr** [comment]
All is working well.
