### ISSUE TITLE
Automatic logout

### ISSUE THREAD

**Issue by diegodblr** [dalibo/ldap2pg#397]
Hi @bersace! 

Do you know how i can automatic logout a user from postgres when this user is removed from a group in active directory?
Because the ldap2pg remove all permission from user when they are removed from the group, but they still connected in the database and only when they make logout, they cant login in the database. I would like to know if is possible to do automatic logout by the ldap2pg.

**Comment by bersace** [comment]
Hi @diegodblr Good point. The idea is to kill backends with targetted user before dropping it ?

**Comment by diegodblr** [comment]
The idea is just logout the user at same time that the user is removed from the active directory group.
 Example: i have two groups in active directory - database1 and database2. My user is in group database1 and i have owner permissions in the database1 on postgresql. I am loged in to this database1. But i resolve to remove my user from database1 group in active directory. Now i am in the database2 group. But i am still loged in the database1 and only if i logout and try to login to database1 i will be denied.  But for security reason, it is better if the ldap2pg when detect the user is out of the group, automatic force logout of this user from the database1.

**Comment by alehaa** [comment]
Maybe we can implement a more general approach like executing a query after `CREATE ROLE`, `ALTER ROLE` and `DROP ROLE`? A default for dropping roles could be the query to kill the session, but other queries like refreshing views could be configured, too.

**Comment by bersace** [comment]
> Maybe we can implement a more general approach like executing a query after `CREATE ROLE`, `ALTER ROLE` and `DROP ROLE`? A default for dropping roles could be the query to kill the session, but other queries like refreshing views could be configured, too.

Yep. What do you think of https://github.com/dalibo/ldap2pg/issues/171#issuecomment-491708103 ?

**Comment by alehaa** [comment]
Thanks for referencing. Think this would solve the feature request, too.
