### ISSUE TITLE
Running the container in podman issues

### ISSUE THREAD

**Issue by PipeItToDevNull** [dalibo/ldap2pg#416]
```bash
> sudo podman run --rm --volume ${PWD}:/workspace dalibo/ldap2pg:latest --verbose --dry
standard_init_linux.go:228: exec user process caused: exec format error
```

No method I have tried to run this container works in podman.

Another run that is more in line with my goal fails with the same error.
```
sudo podman run --pod pg -e LDAP2PG_CONFIG=ldap2pg.yml -d --name ldap dalibo/ldap2pg:5.8
```

**Comment by PipeItToDevNull** [comment]
I was able to `retab` the `docker-entrypoint.sh` and build my own image to get past this?

**Comment by bersace** [comment]
Hi @PipeItToDevNull, can you share your Dockerfile and entrypoint script ? What version of podman do you use ? What is the architecture of your docker host ?

**Comment by bersace** [comment]
Are you running on ARM64 or POWER CPU ?

**Comment by PipeItToDevNull** [comment]
Ahhhhh, it is ARM so that would make sense. I am in the Oracle cloud and it didnt occur to me ARM could be an issue
