### ISSUE TITLE
Can I have multiple postgresql servers?

### ISSUE THREAD

**Issue by testemunha200** [dalibo/ldap2pg#419]
Hi, I was reading the documentation, and I didn't find anything that answer my question.
I'm wondering if I'm able to configure ldap2pg to connect to multiple postgres servers, and not just one.
My setup would be like:
1x LDAP Server
1x LDAP2PG
10x postgres servers, which would need to have the same users / roles

Thanks in advance.

**Comment by bersace** [comment]
Hi @testemunha200 ,

ldap2pg synchronizes a single PostgreSQL server. You need to execute ldap2pg 10 times, each time configured to access a single PostgreSQL server.

Is it clear for you ?

**Comment by testemunha200** [comment]
Hi @bersace got it, thanks. I made a little script that worked great for me, I will include a simplified version because maybe it will help someone:
```
#!/bin/bash
export PGDATABASE=postgres
export PGUSER="USER"
export PGPASSWORD="PASSWORD"

function Execute {
for h in ${HOST[@]}; do
echo $h
export PGHOST="$h"
ldap2pg
echo '####################'
done
}

HOST=('IP_BD_SERVER_1' 'IP_BD_SERVER_2' 'IP_BD_SERVER_3')
Execute
echo 'THE END'
```

**Comment by bersace** [comment]
@testemunha200 good. I suggest you:

``` bash
set -eu  # fail script on error or undefined variable

...
PGHOST="$h" ldap2pg  # Export PGHOST only for one ldap2pg run.
```
