### ISSUE TITLE
Authentication with PostgreSQL - password is in the clear, can it be encrypted

### ISSUE THREAD

**Issue by love2freefly** [dalibo/ldap2pg#420]
HI. My company's security policy won't allow passwords to be stored in the clear, so the yaml file would need to be encrypted. Or ldap2pg would need to read the password from an encrypted source. Integration with Vault might be an option. Is there a way to do this in the current version or are there plans to include this functionality please as without it we cannot use the product and it looks very useful. Thanks!

**Comment by bersace** [comment]
Hi @love2freefly ,

Can you use environment variables ?

Note that ldap2pg refuses to read passwords from a world readable file.

**Comment by bersace** [comment]
Closing stale issue.
