### ISSUE TITLE
Creating users

### ISSUE THREAD

**Issue by sainio** [dalibo/ldap2pg#430]
Hi,
so we have created roles to the database, the role names are the same than ldap group names.
Is it possible to create users into postgres based on their memberOf -status in ldap and so that they have the roles from where the membership comes from?  Role name have a prefix, that can be used as a filter.

**Comment by bersace** [comment]
Hi @sainio,

Yes. Use `ldapsearc:filter` parameter. The content of filter is LDAP specific and depends on what is available in you Directory server. Contact your directory administrator to have documentation and help about writing LDAP filters.

Is it clear for you ?

Regards

**Comment by sainio** [comment]
I have no issue on listing users from ldap, the problem is what do I put into ldap2pg.yaml file to create users.  So far the dry run shows only create roles and that I dot need.

**Comment by bersace** [comment]
Can you share the YAML ?

**Comment by sainio** [comment]
- role:
    name: ldap_roles
    options: NOLOGIN
- ldapsearch:
    base: ou=Groups,dc=local,dc=saminet,dc=fi
    filter: "(cn=sgNZV_DWT*)"
  role:
    name: '{member}'
    options: LOGIN
    parent: ldap_roles

  postgres:
    dsn: postgres://root:XXXXXXX@localhost:5432/

**Comment by bersace** [comment]
Thanks @sainio. Where is the filter on `memberOf`?

**Comment by sainio** [comment]
Do you have any examples on how to setup create users?  All I get out of this with examples is punch of
Would execute: CREATE ROLE "CN=K858064"
type lines and I'm do not want roles, I need users to be created and have a pre-existing role assigned to them, the role has the same name which they are members in ldap.

**Comment by bersace** [comment]
`member` is a distinguished name. If you want to use `sAMAccountName`, you have to reference it with `{member.sAMAccountName}`. This is terrible for performances and you should use `memberOf` instead.

**Comment by sainio** [comment]
so, what kind of a config file will generate CREATE USER statements?

**Comment by sainio** [comment]
So I managed to get this working for one group.  Can I get groups in one query and then loop through those groups on another to get sAMAccountName for the members?

**Comment by bersace** [comment]
Hi @sainio . Yes, this depend on the model of your directory. Something like:

``` yaml
sync_map:
- ldapsearch:
    base: ...
    filter: ...
  roles:
  - name: "{cn}"
    options: NOLOGIN
    comment: "Group for {dn}."
  - name: "{member.cn}"
    parent: "{cn}"
    options: LOGIN
    comment: "Role for {member}."
```

**Comment by sainio** [comment]
This seems to fill my can of beans:

- ldapsearch:
    base: XXX
    filter: "(cn=groups*)"
  role:
    name: '{cn}'
    options: NOLOGIN
    comment: 'From LDAP group {cn}'

- ldapsearch:
    base: XXXXXX
    filter: "(cn=groups*)"
    scope: sub
    joins:
      member:
        filter: '(memberof=*)'
  role:
    name: '{member.sAMAccountName.lower()}'
    options: LOGIN
    parent: '{cn}'
    comment: 'From LDAP group {cn}'

**Comment by bersace** [comment]
Cool. If you're done, please close the issue.
