### ISSUE TITLE
Rerun error after failed drop role

### ISSUE THREAD

**Issue by vikingUnet** [dalibo/ldap2pg#433]
Hello again!

When i updated version ldap2pg to 5.8, i had some errors.

I have run ldap2pg with config on cluster, which was restored from another cluster (that was our mistake along time ago).

First i collect error, that drop user is impossible:
```
[ldap2pg.psql         CHANG] Reassign lookups_editors's objects and purge ACL in context.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] GRANT "lookups_editors" TO postgres;
[ldap2pg.psql         DEBUG] REASSIGN OWNED BY "lookups_editors" TO "postgres";
[ldap2pg.psql         DEBUG] DROP OWNED BY "lookups_editors";
[ldap2pg.psql         CHANG] Drop lookups_editors.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] DROP ROLE "lookups_editors";
[ldap2pg.psql         DEBUG] Closing connection to libpq default.
[ldap2pg.psql         DEBUG] Closing connection to context.
[ldap2pg.script       CRITI] Error while executing SQL query:
[ldap2pg.script       CRITI] role "lookups_editors" cannot be dropped because some objects depend on it
[ldap2pg.script       CRITI] DETAIL:  15 objects in database lookups
```

And after that error postgres is member of lookups_editors:
```
[local]:5433 postgres@postgres=# \du+ postgres
                                              List of roles
 Role name |                         Attributes                         |     Member of     | Description 
-----------+------------------------------------------------------------+-------------------+-------------
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {lookups_editors} | 
```

And next time run will produce that traceback:
```
Unhandled error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ldap2pg/role.py", line 309, in resolve_membership
    member = index_[member_name]
KeyError: 'postgres'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ldap2pg/script.py", line 37, in main
    exit(synchronize(config))
  File "/usr/local/lib/python3.8/dist-packages/ldap2pg/script.py", line 133, in synchronize
    count = manager.sync(syncmap=config['sync_map'])
  File "/usr/local/lib/python3.8/dist-packages/ldap2pg/manager.py", line 297, in sync
    pgallroles.resolve_membership()
  File "/usr/local/lib/python3.8/dist-packages/ldap2pg/role.py", line 311, in resolve_membership
    raise ValueError('Unknown member role %s' % member_name)
ValueError: Unknown member role postgres
Please file an issue at https://github.com/dalibo/ldap2pg/issues with full log.
```

Manually drop grants on all object in databases from that role was not worked for me - there are still 15 objects (i can't find them..). Trying to drop this role:
```
ERROR:  role "lookups_editors" cannot be dropped because some objects depend on it
DETAIL:  15 objects in database lookups
```

Maybe it is warning, but not critical error? 
In fact we can't rerun ldap2pg after this error.
As one of decision, If we have postgres like member of, we can just ignore this role and disable it (set nologin role attribute).

Thanks for reading.

**Comment by bersace** [comment]
Hi @vikingUnet , thanks for reaching.

```
[ldap2pg.psql         DEBUG] Closing connection to libpq default.
[ldap2pg.psql         DEBUG] Closing connection to context.
```

It looks like `postgres:databases` is set to `[context]`. This prevent ldap2pg to reassign/drop assigned objects in other database like `lookups` for instance.

Can you confirm this ?

**Comment by bersace** [comment]
> But if we decide to drop role, why we can't check all existing databases and change owner from dropping role? It may be decide this problem.

This is the purpose of `databases_query` : scope ldap2pg operation on a subset of databases.

> ERROR:  cache lookup failed for relation 1474231

Hmm, that's odd and may not be related to ldap2pg. I never encounter such `cache lookup failed`. You may have more help from DBA in a general PostgreSQL mailing list rather than here. I'd be happy if you share back the anwser.

Is this related to an index ? An old transaction ?

**Comment by vikingUnet** [comment]
> This is the purpose of databases_query : scope ldap2pg operation on a subset of databases.
Databases_query parameter can prevent from this error in most cases, but not at all. Don't you want to raise warning instead error when can't drop role?

Anyway, at next run we have **crush loop** with ValueError at [role.py[line311]](https://github.com/dalibo/ldap2pg/blob/76768ac87dd3331c6f7797a2d46610f6ebd36ff6/ldap2pg/role.py#L311) - _Unknown member role postgres_. It is sad. To repair it we need manually revoke deleted (not at all) role from postgres role. Can we just raise warning or revoke automatically?

> Is this related to an index ? An old transaction ?

no, database was restored from another cluster, yes, it can have some artefacts. But event pg_dump schema didn't detect any owned objects =(

> You may have more help from DBA in a general PostgreSQL mailing list rather than here. I'd be happy if you share back the anwser.

Okey, i will try to ask them later, when will have some much time, thanks for the good idea!

**Comment by bersace** [comment]
> Unknown member role postgres

Can you share a full log output ?

It looks like ldap2pg sync_map tries to modify `postgres` roles while it's on the blacklist. Can you confirm this ?

**Comment by bersace** [comment]
Closing stale issue.
