### ISSUE TITLE
Database exclude

### ISSUE THREAD

**Issue by TezkaRabota** [dalibo/ldap2pg#434]
Hi gurus,
I have 70 databases in my cluster. I want to grant access for my ldap users to 55 of them. Is there an option in ldap2pg configuration to filter the databases we want to be changed by ldap2pg?

**Comment by MHenn1g** [comment]
Hi @TezkaRabota,
maybe have a look into the  [databases_query](https://ldap2pg.readthedocs.io/en/latest/postgres/#what-databases-to-synchronize).
Wit it you may define the databases to be managed by ldap2pg:
e.g. like 
```
postgres:
  databases_query: |
    SELECT datname
    FROM pg_catalog.pg_database
    WHERE datname like 'test%';
```

**Comment by bersace** [comment]
Hi @TezkaRabota , @MHenn1g is right. Does https://ldap2pg.readthedocs.io/en/latest/config/#postgres-databases-query helps ?

**Comment by bersace** [comment]
Closing stale issue.
