### ISSUE TITLE
FATAL:  sorry, too many clients already

### ISSUE THREAD

**Issue by TezkaRabota** [dalibo/ldap2pg#437]
Hi,

I have an issue with  running ldap2pg in my postgresql cluster. I have a cluster with 115 databases. I have 200 active connections and max_connections is set to 300. Initial run of ldap2pg to setup ldap access went OK. But now I get error message every time I run ldap2pg:

[postgres@nnnn ldap2pg]$ ldap2pg -N
Starting ldap2pg 5.8.
Using /data/pgsql/izum_local/ldap2pg/ldap2pg.yml.
Connecting to LDAP server ldaps://...
Trying simple bind.
Running in real mode.
Inspecting roles in Postgres cluster...
Nastavitev role in pravic
Querying LDAP DC=aaa,DC=bbb... (&   (object...
Querying LDAP DC=aaa,DC=bbb... (&   (object...
Querying LDAP DC=aaa,DC=bbb... (&   (object...
Querying LDAP DC=aaa,DC=bbb... (&   (object...
Querying LDAP DC=aaa,DC=bbb... (&   (object...
Querying LDAP DC=aaa,DC=bbb... (&   (object...
Inspecting GRANTs in Postgres cluster...
Unhandled error:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ldap2pg/script.py", line 37, in main
    exit(synchronize(config))
  File "/usr/lib/python3.6/site-packages/ldap2pg/script.py", line 133, in synchronize
    count = manager.sync(syncmap=config['sync_map'])
  File "/usr/lib/python3.6/site-packages/ldap2pg/manager.py", line 330, in sync
    schemas = self.inspector.fetch_schemas(databases, ldaproles)
  File "/usr/lib/python3.6/site-packages/ldap2pg/inspector.py", line 222, in fetch_schemas
    (s.name, s) for s in self.fetch('schemas', Schema, db.name)
  File "/usr/lib/python3.6/site-packages/ldap2pg/inspector.py", line 154, in fetch
    conn = self.pool.getconn(dbname)
  File "/usr/lib/python3.6/site-packages/ldap2pg/psql.py", line 74, in getconn
    connstring, connection_factory=FactoryConnection, **kw
  File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: FATAL:  sorry, too many clients already
Please file an issue at https://github.com/dalibo/ldap2pg/issues with full log.

What is a problem?

**Comment by bersace** [comment]
Hi @TezkaRabota . ldap2pg should handle such error better. What is max_connection in your PostgreSQL instance ?

**Comment by TezkaRabota** [comment]
Hi @bersace . max_connections is set to 300.

**Comment by bersace** [comment]
Thanks. Do you have other messages in PostgreSQL logs ?

**Comment by TezkaRabota** [comment]
Unfortunately this is the only one.

**Comment by TezkaRabota** [comment]
I don't understand it. I get the same error even when running ldap2pg in dry mode.

**Comment by bersace** [comment]
You should investigate `pg_stat_activity` view to discover what happening in your instance. Can you share ldap2pg verbose output ?

**Comment by TezkaRabota** [comment]
I try to reproduce error, but it works now. I run ldap2pg -Nv and found out that number of connections on cluster raised from 165 to 280 connections during ldap2pg run. That means that ldap2pg opened 115 connections at the same time which is exact number of databases in the cluster. This explains the error message from my case. ldap2pg actually reached maximum connections. Is the normal behaviour of ldap2pg to open connections to all databases in the cluster at the same time?

**Comment by bersace** [comment]
Ok, that's regular behaviour. Maybe should we state about this in documentation. I'm not sure whether there is room for optimization of connection usage.

**Comment by TezkaRabota** [comment]
Oh, this is very unpleasent. I will try to solve this problem to use ldap2pg over pgbouncer.

**Comment by bersace** [comment]
ldap2pg 6 now uses a single connection at a time, grouping connection on database to at most open 3 times the connexion on a dedicated databases.

**Comment by zurikus** [comment]
@TezkaRabota hi! 

Was you able to solve this issue and reconfigure ldap2pg to use pgbouncer? 
I have same issue with connection utilization from ldap2pg site in cluster with big amount of databases, but looks like ldap2pg at some point still opens direct connections to postgres cluster and utilizes them all. Not using pgbouncer connection defind in dsn setting of postgres: section in ldap2pg.conf . Looks like inspector.py is responsible for that. 

I'm using 5.9 ldap2pg.

**Comment by TezkaRabota** [comment]
Hi,
No I didn't bother to solve this problem. I run ldap2pg directly against postgresql (port: 5432), becuse pgbouncer is useless in this case.
