### ISSUE TITLE
ensure SASL_MECH is none

### ISSUE THREAD

**Issue by seanzechman** [dalibo/ldap2pg#439]
This is listed on the Configuration page of documentation

"By default, OpenLDAP utils uses SASL and use must explicitly use -x CLI switch to force simple bind authentication. ldap2pg has a different behaviour. ldap2pg does not have default SASL mechanism. If SASL_MECH is empty or undefined, ldap2pg uses simple bind.

If you want to force simple bind, ensure SASL_MECH is none."

Our systems are configured globally with SASL_MECH GSSAPI.  I want to unset this on the user that is launching ldap2pg as our domain does not support Kerberos.  How can we unset this on a user level?  I have tried to put many different combinations in local .ldaprc file but most of them give unsupported method error.

![image](https://user-images.githubusercontent.com/116360033/208986539-1b83752a-3084-43c3-b6fb-22a52ff53776.png)

**Comment by seanzechman** [comment]
Nevermind I found that putting this in my yml file solved my problem
ldap:
  sasl_mech: ''

**Comment by bersace** [comment]
Hi @seanzechman . Thanks for the report. The error message is ugly and the documentation should include an exemple.

**Comment by bersace** [comment]
Hi @seanzechman . Thanks for the report. The error message is ugly and the documentation should include an exemple.

**Comment by seanzechman** [comment]
Hi @bersace - yes an example in the documentation would be helpful!  It was actually pretty easy to bypass once I figured out the correct way to do it :D - thanks for all your work!
