### ISSUE TITLE
Documentation: ToC of Well-Known privileges not showing well 

### ISSUE THREAD

**Issue by arjan-saly-tfs** [dalibo/ldap2pg#440]
Hi, 

In chrome, the Table of contents is not showing well on this page: https://ldap2pg.readthedocs.io/en/latest/wellknown/ , see the screenshot attached: 
![image](https://user-images.githubusercontent.com/104632903/209178255-0035f293-bac4-43f2-a708-bb5c9d400eb6.png)

On several other pages it shows fine....

**Comment by bersace** [comment]
I confirm this. Thanks.
