### ISSUE TITLE
ldap2pg 5.4 to 5.5 getting empty list errors

### ISSUE THREAD

**Issue by dgiffin** [dalibo/ldap2pg#442]
I have a config that worked with v5.4 but with v5.5 I am seeing some new errors (example below) which I don't understand, can you point me in the right direction to explain and resolve them?

Running in dry mode. Postgres will be untouched.
Inspecting roles in Postgres cluster...
Querying LDAP cn=pg_admin,cn=groups,cn... (objectClass...
Missing 'member' from cn=pg_admin,cn=groups,cn=compat,dc=accertify,dc=net. Considering it as an empty list.

**Comment by bersace** [comment]
Hi @dgiffin . 5.5 introduce a detection of typo in attribute. The *Missing member* error is a bug fixed introduced in 5.5 and fixed in 5.6. You must upgrade to 5.6 or better to 5.9.

**Comment by dgiffin** [comment]
Thanks!

**Comment by bsislow** [comment]
our sysadmins can't find 5.9 in the dalibo repo - is it available yet?

**Comment by bersace** [comment]
Sorry, i meant 5.8. 5.9 is not released yet.
