### ISSUE TITLE
ldap2pg config on multiple databases cluster with kubernetes

### ISSUE THREAD

**Issue by SergeArmandVictor** [dalibo/ldap2pg#443]
We wrote our configuration to synchronize AD groups with Postgresql roles on kubernetes cluster and it would run fine.
But we habe more than one database on this cluster and i dont see a possibility to separe the privileges sync between multiple databases.

Am i wrong and it is not possible to synchronize or is there a way?

**Comment by bersace** [comment]
Hi @SergeArmandVictor , thanks for reaching.

`grant` rule has a `database` parameter to scope a grant to one or more database. See https://ldap2pg.readthedocs.io/en/latest/config/#grant-database

Is that what you're seeking ?

**Comment by SergeArmandVictor** [comment]
Thanks for your answer, i saw the issue #441 and it seams to be the same problem.

I will check this and execute some tests. If its the correct solution, i will describe it here and close my request.

**Comment by SergeArmandVictor** [comment]
i try to understand the logic of the ldap2pg but i have some problems:

here is my config:

    privileges:
      # Define `ro` privilege group with read-only grants
      ro:
      - __connect__
      - __select_on_tables__
      - __select_on_sequences__
      - __usage_on_schemas__
      - __usage_on_types__

      # `rw` privilege group lists write-only grants
      rw:
      - __temporary__
      - __all_on_tables__
      - __all_on_sequences__

      # `ddl` privilege group lists DDL only grants.
      ddl:
      - __create_on_schemas__
  
    sync_map:
    - description: "Setup static roles and grants."
      roles:
      - names:
        - readers
        - ldap_roles
        - groupa
        - groupb
        options: NOLOGIN
      - name: writers
        # Grant reading to writers
        parent: readers
        options: NOLOGIN
      - name: owners
        # Grant read/write to owners
        parent: writers
        options: NOLOGIN

      grant:
      - privilege: ro
        role: readers
        schemas: __all__
      - privilege: rw
        role: writers
        schema: __all__
      - privilege: ddl
        role: owners
        schema: __all__
      - privilege: access
        role: groupa
        database: customer
      - privilege: access
        role: groupb
        database: product

    - description: "Query LDAP to create owners."
      ldapsearch:
        base: 'OU=sales,DC=ad1,DC=company'
        filter: "(memberOf=CN=customer_o)"      
        role:
        name: '{member.cn}'
        options: LOGIN CREATEDB
        parent:
        - ldap_roles
        - owners
        - groupa
        comment: "From LDAP group {dn}"

.    - description: "Query LDAP to create writers."
      ldapsearch:
        base: 'OU=sales,DC=ad1,DC=company'
        filter: "(memberOf=CN=customer_w)"
      role:
        name: '{member.cn}'
        options: LOGIN
        parent:
        - ldap_roles
        - writers
        - groupa
        comment: 'From LDAP groupe {dn}'

    - description: "Query LDAP to create readers."
      ldapsearch:
        base: 'OU=sales,DC=ad1,DC=company'
        filter: "(memberOf=CN=customer_r)"
      role:
        name: '{member.cn}'
        options: LOGIN
        parent:
        - ldap_roles
        - readers
        - groupa

    - description: "Query LDAP to create owners."
      ldapsearch:
        base: 'OU=production,DC=adserver,DC=company'
        filter: "(memberOf=CN=production_o)"      
        role:
        name: '{member.cn}'
        options: LOGIN CREATEDB
        parent:
        - ldap_roles
        - owners
        - groupb
        comment: "From LDAP group {dn}"

.    - description: "Query LDAP to create writers."
      ldapsearch:
        base: 'OU=production,DC=ad1,DC=company'
        filter: "(memberOf=CN=production_w)"
      role:
        name: '{member.cn}'
        options: LOGIN
        parent:
        - ldap_roles
        - writers
        - groupb
        comment: 'From LDAP groupe {dn}'

    - description: "Query LDAP to create readers."
      ldapsearch:
        base: 'OU=production,DC=ad1,DC=company'
        filter: "(memberOf=CN=production_r)"
      role:
        name: '{member.cn}'
        options: LOGIN
        parent:
        - ldap_roles
        - readers
        - groupb

I have 3 logical privileges groups for owners, writers and readers and 2 databases one for sales and one for products.

1 department is sales with database customer and the second is production with database product.

Is my configuration correct to manage the privileges separatly for the 2 databases?

Thanks in advance for your help

**Comment by bersace** [comment]
Hi @SergeArmandVictor , there is misformating in your comment, It's hard to tell how this configuration can't lead to a YAML error.

I you have two database in the same instance, you must have separate groups for each privileges:

``` yaml
privileges:
  - ro: ...
  - rw: ...
  - ddl: ...
 
sync_map:
  - role:
      name: customer_reader
      options: NOLOGIN
    grant:
      privilege: ro
      role: customer_reader
      database: customer
      schemas: __all__

  - role:
      name: product_reader
      options: NOLOGIN
    grant:
      privilege: ro
      role: product_reader
      database: product
      schemas: __all__
...
```

**Comment by SergeArmandVictor** [comment]
Hello,Thanks but i solved the probleme and have now a ldap config related to individual databases and schemas.Serge Am 03.04.2023 um 09:52 schrieb Étienne BERSAC ***@***.***>:﻿
Hi @SergeArmandVictor , there is misformating in your comment, It's hard to tell how this configuration can't lead to a YAML error.
I you have two database in the same instance, you must have separate groups for each privileges:
privileges:
  - ro: ...
  - rw: ...
  - ddl: ...
 
sync_map:
  - role:
      name: customer_reader
      options: NOLOGIN
    grant:
      privilege: ro
      role: customer_reader
      database: customer
      schemas: __all__

  - role:
      name: product_reader
      options: NOLOGIN
    grant:
      privilege: ro
      role: product_reader
      database: product
      schemas: __all__
...
