### ISSUE TITLE
Setting configuration_parameters via ldap2pg

### ISSUE THREAD

**Issue by randvoorhies** [dalibo/ldap2pg#512]
I would love to be able to set `log_statement TO 'mod'` for some of the roles that are synced by ldap2pg.  Is there any way to pull this off (e.g. https://www.postgresql.org/docs/current/sql-alterrole.html).

I quickly grepped through the code, and didn't see any relevant `ALTER USER ... SET ...` commands anywhere.  If this isn't currently possible, I'd love to put in a feature request. If someone can point me in the correct direction I could probably put in an MR for it.

**Comment by bersace** [comment]
Nice feature !

**Comment by randvoorhies** [comment]
> Nice feature !

Cool, I'll see what I can do :)

**Comment by randvoorhies** [comment]
Ok @bersace piece of cake - I have a WIP branch over here if you want to check it out: https://github.com/randvoorhies/ldap2pg/commits/configuration_parameters

I have a bit more cleanup/docs to do then I'll submit a real PR if you're ok with it.

**Comment by randvoorhies** [comment]
PR is ready to roll.  I haven't added any tests, but let me know if that's a requirement and I'll see what I can do.
