### ISSUE TITLE
Ignore dummy entry that exists in empty groups

### ISSUE THREAD

**Issue by guruguruguru** [dalibo/ldap2pg#544]
## What do you want?

Hey, when I create an empty ldap group this gets filled with a dummy entry by our ldap-management-team with a dummy account (uid=NULL).

So if I now query the empty group it returns uid=NULL as a member which then results in an error:

2023-08-15 15:56:20,099 CRITICAL:  ldap2pg.script: Failed to query LDAP: {'msgtype': 101, 'msgid': 5, 'result': 32, 'desc': 'No such object', 'ctrls': []}.

Can I exlude this member from the search? I am bit stuck, right now.

## ldap2pg.yml
Not sure if this is needed?

**Comment by bersace** [comment]
Could you filter this using regular LDAP filter ?

**Comment by bersace** [comment]
Closing stalled issue.
