### ISSUE TITLE
Docker image misses bash dependency

### ISSUE THREAD

**Issue by mlromramse** [dalibo/ldap2pg#548]
## ldap2pg.yml

<details><summary>ldap2pg.yml</summary>
``` yaml
postgres:
  ...

sync_map:
  ...
```
</details>

## Expectations

- What you expected from ldap2pg ?
   - That is works
- What ldap2pg did wrong ?
   - Return error message immediately

## Verbose output of ldap2pg execution

<details><summary>Verbose output</summary>
``` console
$ ls -la ${PWD}/ldap2pg/Docker
total 2
drwxr-xr-x 3 user user 4096 Aug 18 08:23 .
drwxr-xr-x 3 user user 4096 Jun 15 07:43 ..
-rwxr-xr-x 1 user user 8553 Aug 21 18:15 ldap2pg.yml
-rw-r--r-- 1 user user  141 Aug 18 09:27 ldaprc

$ podman run -v ${PWD}/ldap2pg/Docker:/workspace docker.io/dalibo/ldap2pg:latest --verbose
{"msg":"exec container process (missing dynamic library?) `/usr/local/bin/docker-entrypoint.sh`: No such file or directory","level":"error","time":"2023-08-21T16:22:08.580526Z"}

$ podman run -it --entrypoint='' -v ${PWD}/ldap2pg/Docker:/workspace docker.io/dalibo/ldap2pg:latest head /usr/local/bin/docker-entrypoint.sh
#!/bin/bash
#
# Bootstrap script for running ldap2pg in container.
#
# This script is mostly stolen from Docker official Postgres image.
#

set -eu
shopt -s nullglob

```
</details>

To me it is odd that the docker-entrypoint.sh rely on bash since bash is missing in the alpine base image.

Furthermore it seems that the latest is v6.0-alpha5. Shouldn't latest be a production version?

**Comment by bersace** [comment]
Hi @mlromramse , thanks for the report.

Production should pin image with version tag.

latest points to master and can break. If you have an idea on how to test an image built on docker hub before it's released, I'd be happy.

Regards,
Étienne

**Comment by mlromramse** [comment]
Hi @bersace !
Do I understand you correctly that you rely on docker hub to build your images?
Personally I build locally and test locally before I push to docker hub.
I always use tags in production though but have found that most project-images on docker hub with tag latest point to latest functional image. I your case that would be 5.9. 
E.g. https://hub.docker.com/_/bash/tags where tag latest point to image with tag 5.2.15 even tough they have newer devel version.

**Comment by bersace** [comment]
hi @mlromramse 

good point. I could rename latest to `nightly` and point latest to last stable tag. what do you think of this ?

**Comment by mlromramse** [comment]
Hi @bersace !

I think that sounds like a good approach, that would assure that your section on docker images in your cookbook would always work. (Something I noticed after my last comment)

Thank you for addressing this issue in a prompt manner!

Best Regards

Mikael
