### ISSUE TITLE
ldap2pg without user?

### ISSUE THREAD

**Issue by peteerwhite** [dalibo/ldap2pg#552]
Hello all,

I wanted to ask if it is also possible to use ldap2pg without specifying a user in the config.

If I work with ldapsearch via the CLI the command "ldapsearch -x -h ... -b ..." is enough to get the necessary information.

Can I also configure this in ldap2pg.yml? Or do I have to specify a user?

Thanks for the help and kind regards

**Comment by bersace** [comment]
hi @peteerwhite , thanks for reaching.

what is the output of ldapwhoami -d 3 ?

Regards

**Comment by peteerwhite** [comment]
hi @bersace,
thanks for the quick reply, but I could already solve my problem by setting the environment variable LDAPURI.
Regards
