### ISSUE TITLE
ldap2pg 6 in RHEL9 dalibolabs repo

### ISSUE THREAD

**Issue by dani** [dalibo/ldap2pg#568]
Not a bug per se, just a request for confirmation : dalibolabs yum repo used to provide python based ldap2pg, and in is now offering an upgrade to the new Go version. But only for RHEL7 and RHEL8. The repo for RHEL9 is almost empty, and ldap2pg is absent. Is that expected ? (Just to know if I have to update my deployement cookbook to switch from RPM based install to manual binary install)

**Comment by bersace** [comment]
hello @dani, good point ! thanks for the feedback.

**Comment by bersace** [comment]
note that the binary is exactly the same across all distributions and versions.

**Comment by bersace** [comment]
It's uploaded. Closing.
Please reopen if anything.
