### ISSUE TITLE
ldap2pg bind user and password

### ISSUE THREAD

**Issue by jschmidwgit** [dalibo/ldap2pg#574]
## What do you want?

I want to set up ldap2pg, i understand the basic concept and the default configuration. However i am not able to set a bind user for the ldap queries. I need to provide a user and a password. When i try to set this in .ldaprc it simply does not work. I get either a
"err="LDAP Result Code 206 \"Empty password not allowed by the client\": ldap: empty password not allowed by the client""

or 
panic: runtime error: index out of range [1] with length 1

goroutine 28 [running]:
github.com/dalibo/ldap2pg/internal/ldap.iterFileOptions.func1()
        /workspace/internal/ldap/rc.go:186 +0x189
created by github.com/dalibo/ldap2pg/internal/ldap.iterFileOptions
        /workspace/internal/ldap/rc.go:172 +0x10a

i try tp use .ldaprc with these entries:
ldapbinddn cn=xxxxx,dc=emea,dc=corpds,dc=net
ldapbindpasswd=yyyyy

what is the basic idea to use ldap with a user and a password? And why is it not mentioned in any documentation?

## ldap2pg.yml

<details><summary>ldap2pg.yml</summary>
``` yml
...
```
</details>

**Comment by jschmidwgit** [comment]
Ok, i found it - it is working with the environment variables only, and not with the .ldaprc

**Comment by bersace** [comment]
Hi @jschmidwgit , thanks for the feedback.

Can you share how to triggered the panic ? I want to fix this.

I plan to load .env file in ldap2pg as a complement of ldaprc. This should ease configuring access in files.

**Comment by jaldama** [comment]
you actually can put your password in .ldaprc. The keyword is 'PASSWORD' without ':' or '='. In my case, the .ldaprc file is in my home directory:

`[postgres@postgreshost ~]$ cat .ldaprc
URI ldaps://test.org:5856

BINDDN cn=Manager,dc=example,dc=com

TLS_REQCERT allow

PASSWORD password`

As far as ldap2pg.yml, for v6.3, all you need in the yaml is the Version and Rules section:

`[postgres@postgreshost ~]$ cat test2.yml 
version: 6

rules:
  - description: Sync LDAP users from ou=People to PostgreSQL roles`

Would be nice if these values could be kept in the yaml and decoded/mapped to the ldap client upon ldap2pg execution, but unfortunetly it doesnt work taht was as of v6.3
