### ISSUE TITLE
Assign Roles to Users

### ISSUE THREAD

**Issue by jschmidwgit** [dalibo/ldap2pg#576]
Hello,

i want to add all members of an ad/ldap group which contains dba-Accounts to the database. From this group all members should become dbas on the database and i want them to be in a postgresql-role named 'dba'.

I understand, how individual users can be created, but not how i can add the new users from the ldap-directory  to a postgresql group. I did not find any matching example in the documentation.

Jan

**Comment by bersace** [comment]
Hi @jschmidwgit thanks for reaching.

Did you read master [ldap2pg.yml](https://github.com/dalibo/ldap2pg/blob/master/ldap2pg.yml) ?

**Comment by jschmidwgit** [comment]
Yes, but i don't really understand it. Maybe it is because it is the first time that i work with ldap.

I see this part:
- description: "Search LDAP to create readers, writers and owners."
  ldapsearch:
    base: ou=groups,dc=ldap,dc=ldap2pg,dc=docker
    filter: "
    (|
      (cn=owners)
      (cn=readers)
      (cn=writers)
    )
    "
  role:
    name: '{member.cn}'
    options: LOGIN
    parent: "{cn}"

What i understand is that this ldap search looks in ou=groups,dc=ldap,dc=ldap2pg,dc=docker for users. But the username is for example user1 so i don't understand what this cn=owners, cn=readers, and cn=writers mean, I thought i get a list of users and would like to add them to a postgresql group. So from what i understand your script creates the role with login for the usernames found in ldap. So does this role that i want (for example dba) has to exist in ldap for this to work? I thought i get a list of names and do something like this with it:
  role:
    name: '{member.cn}'
    options: LOGIN
    parent: "{cn}"
    role dba
then i would understand it, if i can assign a role to the user. But where is the role assigned in this sample configuration?

and about the privilege part: i don't understand where this connects to the LDAP entries.

 grant:
  - privilege: ro
    role: readers
    # Scope to a single schema
    schemas: nominal
  - privilege: rw
    role: writers
  - privilege: ddl
    role: owners

Ok, the role owners has the ddl privilege. But where do these roles  "owners" and "writers" get assigned to a user? I just don't get the connection between the ldap users and the roles that i want to assign.

rules:
- description: "Setup static roles and grants."
  roles:
  - names:
    - readers
    options: NOLOGIN
  - name: writers
    # Grant reading to writers
    parent: readers
    options: NOLOGIN
  - name: owners
    # Grant read/write to owners
    parent: writers
    options: NOLOGIN

**Comment by bersace** [comment]
Set `parent: dba` to the role rule creating your DBA. This will make them member of `dba` role.

**Comment by bersace** [comment]
> Hello, ok now i am beginning to understand. I did not understand that the value parent represents the role.

Would `memberof` be more explicit/evident than `parent` ?

**Comment by bersace** [comment]
I'm thinking of a client side `if`.
But I'm not sure about the design.

The best solution is to simply use an attribute with the right value:

``` yaml
- ldapsearch: ...
  role:
    parent: "{parent}"
```

I'm also wondering of a feature like `{attribute.match('_(write|read|admin')}' to extract a value from an attribute.

Tell me what you think would be the best solution.

**Comment by jschmidwgit** [comment]
> > Hello, ok now i am beginning to understand. I did not understand that the value parent represents the role.
> 
> Would `memberof` be more explicit/evident than `parent` ?

For me this was the main point why i misunderstood the configuration. However it would be enough, if it is mentioned somewhere in the documentation that parent stands for the assigned role of the user. But maybe only i had a problem with this. 

thanks for your quick support.

**Comment by bersace** [comment]
> > > Hello, ok now i am beginning to understand. I did not understand that the value parent represents the role.
> > 
> > 
> > Would `memberof` be more explicit/evident than `parent` ?
> 
> For me this was the main point why i misunderstood the configuration. However it would be enough, if it is mentioned somewhere in the documentation that parent stands for the assigned role of the user. But maybe only i had a problem with this.

What did you think `parent` was for ?

**Comment by bersace** [comment]
Closing stale issue.
