### ISSUE TITLE
ldap2pg 6 in official postgres-common repository

### ISSUE THREAD

**Issue by guruguruguru** [dalibo/ldap2pg#595]
Hey,

I have a question about providing the RPMs in the official PostgreSQL Yum Repo (https://download.postgresql.org/pub/repos/yum/com)
Right now the latest version on there is 5.9 and I am a bit afraid that when ldap2pg 6 is pushed to those repos it will break my setups.
Can you elaborate about your plans here? So I would maybe pin the 5.9 versions until we have prepared our deplyoments for ldap2pg6. I understand that the config file is not compatible between the 2 versions, right?

Thanks,
Dennis

**Comment by bersace** [comment]
Hi @guruguruguru . We don't have control on PGDG repositories. We ship updated and supported packages at https://yum.dalibo.org/labs and https://apt.dalibo.org/labs .

It's a good practice to pin ldap2pg package.

ldap2pg 6 will fail to execute a ldap2pg 5 configuration. Thus, your Postgres instance will be safe. ldap2pg will tell you that you need a configuration upgrade.

**Comment by guruguruguru** [comment]
This is great, thank you! I will ask in the PGDG Tracker and pin the packages.
