### ISSUE TITLE
Support setuptools version shipped with RHEL 7

### ISSUE THREAD

**Issue by devrimgunduz** [dalibo/ldap2pg#87]
Hi,

This package builds fine on my Fedora 26 box, but I'm having issues on RHEL 6, RHEL 7 and Fedora 25.

`-bash-4.2$ python setup.py bdist
running bdist
running bdist_dumb
running build
installing to build/bdist.linux-x86_64/dumb
running install
running install_egg_info
running egg_info
writing requirements to UNKNOWN.egg-info/requires.txt
writing UNKNOWN.egg-info/PKG-INFO
writing top-level names to UNKNOWN.egg-info/top_level.txt
writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
reading manifest file 'UNKNOWN.egg-info/SOURCES.txt'
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
`
...and this UNKNOWN word leads to other issues as you can guess.

BTW, this command also does not build ldap2pg binary, too.

Can you please let me know how to build ldap2pg on RHEL 7?
Regards, Devrim

**Comment by bersace** [comment]
Hi @devrimgunduz 

You need a recent `setuptools` that supports `setup.cfg` metadata.

**Comment by bersace** [comment]
@devrimgunduz Here is how i build a `rpm` : https://github.com/dalibo/ldap2pg/blob/master/packaging/build_rpm.sh . Does this help you ?

**Comment by bersace** [comment]
Hi @devrimgunduz , do you have some update on this ? I can make `setup.py` compatible with setuptools shipped with RHEL 7.

**Comment by devrimgunduz** [comment]
Hi @bersace . Apologie for the late response, I missed your previous comment. That does not help, because RPM builds are not allowed to install anything external, like pip 

FWIW, I build similar packages which use setup.cfg, on RHEL 6 and RHEL 7, like psycopg. What is different in ldapfdw?

**Comment by bersace** [comment]
Ok, I have to make it compatible.

`ldap2pg` puts *metadata* in setup.cfg, following the effort of pypa to be able to build python package without boilerplate (only a setup.cfg). That's just a nice to have. See http://setuptools.readthedocs.io/en/latest/history.html#v30-3-0

setuptools is quite active. But let's support RHEL 7 setuptools.

**Comment by bersace** [comment]
Hi @devrimgunduz I uploaded ldap2pg 2.1a1 with #90 merged. Can you test it ?

**Comment by bersace** [comment]
@devrimgunduz version 3.0 is shipped with the fix. Please reopen if you still encounter error ! Regards.

**Comment by devrimgunduz** [comment]
Hi,

Thank you! I built and pushed the RPMs. They will be available in next 40 mins.

Regards, Devrim
